### ISSUE TITLE
Issues installing packages, macOS ARM64 version

### ISSUE THREAD

**Issue by oresttokovenko** [conda-forge/miniforge#102]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Whenever I try to install almost any package, I get 
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

````

For example, I can't even install Jupyter Notebooks. Please advise. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
Was this meant to be closed?

In any event this work is ongoing (and there is plenty to do in case you are interested in chipping in 😉). The status of the work can be seen [here]( https://conda-forge.org/status/#armosxaddition ). Any packages that are not on that list and are needed can be added to [this list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt ).

**Comment by oresttokovenko** [comment]
I did close it because I gave up on ARM64 Miniforge and went back to x86 Miniconda, because I wasn't not able to install any packages, I kept getting version errors and whatnot. Strange, because according to your link many packages are available, but I couldn't even install Jupyter. I'll try again and post my errors if I encounter them.

**Comment by isuruf** [comment]
@oresttokovenko, `jupyter` is not available yet. You can install `notebook` for now

**Comment by isuruf** [comment]
`jupyter` should be available now

**Comment by hmaarrfk** [comment]
:)

**Comment by oresttokovenko** [comment]
Thank you! I went back to Miniforge and installed Jupyter
