### ISSUE TITLE
Strange bug with Miniforge3-MacOSX-arm64, doesn't show envs from base

### ISSUE THREAD

**Issue by oresttokovenko** [conda-forge/miniforge#103]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm using Miniforge3-MacOSX-arm64 version of MiniForge, and when I'm in my base environment, I can't see my other environments, unless I activate one of them and run `Conda list env`. I attached a screenshot. I was using Miniconda before and this never happened.

<img width="641" alt="Screen Shot 2021-01-21 at 11 48 20 PM" src="https://user-images.githubusercontent.com/51058259/105457054-71fe7d80-5c43-11eb-94c7-392fb97c318d.png">

**Comment by isuruf** [comment]
In your first command, you used `conda list env` instead of `conda env list`.

**Comment by oresttokovenko** [comment]
haha that's a silly mistake! Thanks for the correction!
