### ISSUE TITLE
Make a flag to disable "Extracting xyz.tar.bz2" output in terminal

### ISSUE THREAD

**Issue by inducer** [conda-forge/miniforge#113]
Currently, miniforge appears to always print a number of rapidly-updating lines of `Extracting xyz.tar.bz2`. Use in CI jobs then leads to annoying log spam like in this log: https://github.com/inducer/pytential/pull/58/checks?check_run_id=1873240515. I hunted for a way to turn it off, but I was unsuccessful. I didn't even find the place where it's printed. (from within conda?) Output redirection is a nonstarter as a solution unfortunately, as the messages are sent on stderr. Redirecting that would get rid of error messages, too.

**Comment by isuruf** [comment]
Code is at https://github.com/conda-forge/conda-standalone-feedstock/blob/master/recipe/entry_point.py#L68 and is called by https://github.com/conda/constructor/blob/master/constructor/header.sh#L414

**Comment by isuruf** [comment]
If we use `tqdm.tqdm(disable=None)` progress bar will be disabled on non-TTY.

cc @nehaljwani

**Comment by isuruf** [comment]
Should be fixed now. The messages are sent to stdout.
