### ISSUE TITLE
Exec format error for arm64 architecture

### ISSUE THREAD

**Issue by 8greg8** [conda-forge/miniforge#114]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
When using `bash Miniforge3-Linux-aarch64.sh` on Raspberry 3B I get

```
PREFIX=/home/pi/miniforge3
Unpacking payload ...
Miniforge3-Linux-aarch64.sh.1: line 318: /home/pi/miniforge3/conda.exe: cannot execute binary file: Exec format error
Miniforge3-Linux-aarch64.sh.1: line 320: /home/pi/miniforge3/conda.exe: cannot execute binary file: Exec format error
```

There is an .exe file in miniforge3 which is a windows binary

**Comment by hmaarrfk** [comment]
what OS are you using on the raspeberry pi? I believe the standard raspbian is 32 bit, not 64.

We only build for 64 bit OS.

**Comment by xflcx1991** [comment]
@hmaarrfk I change to arm64 by add `arm_64bit=1` to `config.txt`,then reboot and `uname -m` get `aarch64`.Still get `conda.exe`.

**Comment by xflcx1991** [comment]
> Did you download the RasbianOperating system. To my knowledge, we don't support raspbian

Yes,I use raspbia-pi-os on Raspberry Pi 3 model B.Ok,I'll try other os system.

**Comment by hmaarrfk** [comment]
To my knowldge, anything downloaded from this website,
https://www.raspberrypi.org/software/operating-systems/

that is compatible with *all raspbery pi products* is 32 bit.

You should download something like
https://ubuntu.com/download/raspberry-pi

which specifies a 64 bit version.

32bit OS will RUN on 64 bit hardware. You simply won't be able to install miniforge.

**Comment by hmaarrfk** [comment]
@8greg8 I am inclined to close this issue if you don't have any other questions.
