### ISSUE TITLE
Build Raspbian ARM 32 bit

### ISSUE THREAD

**Issue by rodrykthingol** [conda-forge/miniforge#115]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Installing miniforge on raspbian 32 bit

<br/>
Environment (<code>conda list</code>):
<details>
Hello, i've been trying to build miniforge on a raspberry pi. The problem is that i'm a complete newb. I've tried editing the configuration on the build shell to armv7, but no success.

Last recourse would be to install the beta version arm64 raspbian. Though that would break cause some other issues.
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
We don't support arm 32 bit.

**Comment by hmaarrfk** [comment]
I have to say I'm not too excited about this.

Migrating to arm64 has taken quite a few resources, and soon enough, raspbian is going to likely deprecate the 32bit builds.

If 32 bit is not possible for you, then conda-forge is likey not the solution for you.
