### ISSUE TITLE
Automatic PRs for conda and mamba updates

### ISSUE THREAD

**Issue by xhochy** [conda-forge/miniforge#116]
In #110 I pinned the `mamba` version and also volunteered between the lines to write some automation to update that version. Normally I would implement that in Github Actions but my usual approach requires a technical user and also puts load on GHA. Thus we should probably leverage the cf-scripts for this. @conda-forge/bot Any pointers where I could hook into to let the bot make PRs here?

**Comment by beckermr** [comment]
I think it is easier to use GHA here. A job that boots up once a day and checks for updated versions will be fine.

**Comment by beckermr** [comment]
The bot needs a feedstock to make PRs so it won't work here.
