### ISSUE TITLE
Miniforge3 is installing Python 3.9.1 in the base environment:

### ISSUE THREAD

**Issue by kaili-yang** [conda-forge/miniforge#118]
My PC:
M1 Macbook
BigSur 11.0.1

Installation:
OS X | arm64 (Apple Silicon) (**) | Miniforge3-MacOSX-arm64

Issue:
As you can see in the screenshot, this package installed Pyhon3.9 but I need python 3.8.

I have tried many other methods like manually uninstall and delete all relevant python3.9 and reinstall Miniforge3-MacOSX-arm64  but it still doesn't work.

![image](https://user-images.githubusercontent.com/79012058/108592841-e6dfe700-73aa-11eb-8597-39b2025fc33f.png)

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hmaarrfk** [comment]
New hardware, means new software. 

Officially only python 3.9 is supported on M1 macbook, and we are still migrating much of the software.

**Comment by isuruf** [comment]
You can create a new python=3.8 environment. (It's not supported officially by python upstream, but it should work reasonably, but YMMV)
