### ISSUE TITLE
Raspberry pi3+, 64bit kernel, conda.exe not found

### ISSUE THREAD

**Issue by abebeos** [conda-forge/miniforge#120]
## Reproduction

* Pick a Raspberry Pi3+ or 4
* Install the 32bit Raspberry Pi OS (armv7l)
* Switch it to 64bit kernel (becomes aarch64)
    * https://www.sindastra.de/p/1345/switch-your-raspberry-pi-to-64-bit-kernel-raspbian/
* Install miniforge3

```sh
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh
chmod +x Miniforge3-Linux-aarch64.sh
./Miniforge3-Linux-aarch64.sh # follow through manually, usually  [ENTER] or "yes"

...
Unpacking payload
./Miniforge3-Linux-aarch64.sh: 318: ././Miniforge3-Linux-aarch64.sh: /home/pi/miniforge3/conda.exe: not found
``` 

This should(!) work, but it does not.

`conda.exe` is actually there, but not executable.

(on the the 64bit beta of Raspberry Pi OS it works fine.)

**Comment by isuruf** [comment]
We don't support `armv7l`. We support only `aarch64`.

**Comment by abebeos** [comment]
@isuruf, please reread, this is about aarch64.

In any case, closing issues that fast is a bit off.

**Comment by isuruf** [comment]
Can you show the output of `uname -a`?

**Comment by abebeos** [comment]
(typing it manually from other screen)

`Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 20 (...) aarch64 GNU/Linux`

**Comment by isuruf** [comment]
what do you get with `/home/pi/miniforge3/conda.exe --help`?

**Comment by abebeos** [comment]
"no such file or directory"

(is it always *.exe on linux? )

**Comment by isuruf** [comment]
> (is it always *.exe on linux? )

Yes.

there's no file called `/home/pi/miniforge3/conda.exe` at all?

**Comment by abebeos** [comment]
> conda.exe is actually there, but not executable.

The linux kernel on the pi is switched to 64bit, but all installed applications remain 32bit. But htis should work, see https://www.sindastra.de/p/1345/switch-your-raspberry-pi-to-64-bit-kernel-raspbian/

is there any debug switch at the installer?

**Comment by isuruf** [comment]
Do you have a loader that can load 64 bit executable? You might have to install the 64 bit version of glibc as well.

**Comment by abebeos** [comment]
> Do you have a loader that can load 64 bit executable? You might have to install the 64 bit version of glibc as well.

Nice, it looks that you've identified the problem, found something relevant here:

https://unix.stackexchange.com/questions/166755/home-amnesia-myfile-command-not-found-64-bit-executable-64-bit-kernel/167145#167145

So, the next step would be I guess:

* How to install 64bit loader?
* How to install 64bit glibc?

**Comment by isuruf** [comment]
You can download https://anaconda.org/conda-forge/sysroot_linux-aarch64/2.17/download/noarch/sysroot_linux-aarch64-2.17-h4744778_10.tar.bz2 where you can find the loader and glibc. Not sure how to make the OS use those. Maybe ask a question on stackoverflow?

**Comment by abebeos** [comment]
Very nice, I'll try those, thanks. I'll read a little around and finally go to forums/SO, or the 64bit pi project (they should know). Leaving issue open until I solve an report back?

**Comment by abebeos** [comment]
Note to readers: seems like the way to go is to use 64bit OS immediately, to avoid troubles (see especially the 2nd page of the topic) :

https://www.raspberrypi.org/forums/viewtopic.php?p=1638330#p1638330

**Comment by abebeos** [comment]
Copying the lib64 files from a raspberry pi os 64bit seems to work:

https://www.raspberrypi.org/forums/viewtopic.php?p=1797332#p1797332

but one comment before, again it is suggested to use the real 64 bit version. 

I start to thing that copying the lib64 files should be fine (if I overcome my laziness to actually  try this, I'll report the steps)

**Comment by abebeos** [comment]
This seems to be a better solutions (can be automated via script) :

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=275398&p=1668320

**Comment by hmaarrfk** [comment]
Thank you two for getting to the bottom of this.

**Comment by abebeos** [comment]
@hmaarrfk , you're welcome (curious: now don't tell me that MCAM uses Pi? )

@all

Final "hope" comes possibly up here:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=304770

**Comment by hmaarrfk** [comment]
> @hmaarrfk , you're welcome (curious: now don't tell me that MCAM uses Pi? )

Happy to talk about this on a different forum! Just message me privately
