### ISSUE TITLE
New updates aren't appearing in brew

### ISSUE THREAD

**Issue by mhdmyz** [conda-forge/miniforge#121]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi. I installed miniforge using `brew install miniforge` command in my mac terminal but I can't update it to the newer releases (Miniforge3-4.9.2-6 or Miniforge3-4.9.2-7) using the `brew update miniforge` command. After 4 days the version shown in the brew website is still Miniforge3-4.9.2-5! (reference: https://formulae.brew.sh/cask/miniforge) When are they going to be available on brew? Thanks!

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
We don't have control on brew release. Please open an issue in https://github.com/Homebrew/homebrew-cask
cc @domoritz

**Comment by isuruf** [comment]
Also, you can update conda packages by doing `conda update conda python`

**Comment by domoritz** [comment]
Someone already did it in https://github.com/Homebrew/homebrew-cask/pull/100158

**Comment by mhdmyz** [comment]
> @adithyasunil26 already did it in [Homebrew/homebrew-cask#100158](https://github.com/Homebrew/homebrew-cask/pull/100158)

Thank you!

**Comment by domoritz** [comment]
Anyone can send a pull request with `brew bump-cask-pr`. Note that there is a bug in brew right now so the hashes for arm64 don't get updated if you are not running on arm. I hope they fix that eventually (https://github.com/Homebrew/homebrew-cask/issues/100230).

**Comment by mhdmyz** [comment]
> Anyone can send a pull request with `brew bump-cask-pr`. Note that there is a bug in brew right now so the hashes for arm64 don't get updated if you are not running on arm. I hope they fix that eventually ([Homebrew/homebrew-cask#100230](https://github.com/Homebrew/homebrew-cask/issues/100230)).

Yeah I'm running miniforge on arm (Apple M1), but I was able to update it (thanks to you!) using the brew update command.

**Comment by hmaarrfk** [comment]
I'm going to close this as keeping the brew package updated isn't something we have control over and this original issue is 4 months old. it seems that the mentionned issues and PRs have been closed in the appropriate locaiton.
