### ISSUE TITLE
License file still states 2020 - update to 2021?

### ISSUE THREAD

**Issue by jasonmvictor** [conda-forge/miniforge#123]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
A PR would be welcome 🙂

**Comment by hmaarrfk** [comment]
Closed by https://github.com/conda-forge/miniforge/pull/124

**Comment by hmaarrfk** [comment]
Thanks for bringing this up!

**Comment by jasonmvictor** [comment]
Wow, that's a fast turnaround!  :) 👍
