### ISSUE TITLE
Miniforge Installer - Exec format error

### ISSUE THREAD

**Issue by dual19** [conda-forge/miniforge#144]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Miniforge Installer - Exec format error
I'm trying to install Miniforge on a Raspberry Pi 3b+, with
```
bash Miniforge3-Linux-aarch64.sh
```
However, I'm running into the following error.
This seems to be an error with the install script, since it is trying to run an .exe file on the Raspberry Pi OS. Or, I could be making an obvious mistake. 

<br/>
Error Message:
<details>

```
PREFIX=/home/pi/miniforge3
Unpacking payload ...
Miniforge3-Linux-aarch64.sh: line 318: /home/pi/miniforge3/conda.exe: cannot execute binary file: Exec format error
Miniforge3-Linux-aarch64.sh: line 320: /home/pi/miniforge3/conda.exe: cannot execute binary file: Exec format error

```

**Comment by hmaarrfk** [comment]
Raspberry Pi OS is a 32 bit OS.

MIniforce only works with 64 bit processors, and 64 bit OS.

Please install a linux distribution that has a 64bit kernel on your Raspberry Pi Hardware.

I would also contact the Raspberry PI Foundations and let them know that 64 bit support is important to you.

**Comment by dual19** [comment]
Okay, that is explains it. Thank you!
