### ISSUE TITLE
Difference between miniconda and miniforge

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda-forge/miniforge#147]
I am trying to write the docs for miniforge in the conda-forge main documentation.

While doing research I came across this:
https://stackoverflow.com/questions/60532678/what-is-the-difference-between-miniconda-and-miniforge

It would be great if members of the miniforge team could answer this question clearly. It'll allow me to write better docs. :)
Thanks.

Also see: https://github.com/conda-forge/conda-forge.github.io/issues/1356

**Comment by ForgottenProgramme** [comment]
@hmaarrfk

**Comment by hmaarrfk** [comment]
I'm not sure I want to focus on differences. Those are hard to maintain and keep track of. I am also not a lawyer, so i worry about giving legal advice. (I'm not sure that anaconda can restric access to GPL software bases on their different purposes)

Simply say that it is a way to install conda with a community managed channel, conda-forge set as the default channel.

**Comment by ForgottenProgramme** [comment]
Yes. I do understand. 

The difference between the two (miniconda and miniforge) might not seem very important, but look here:

"If miniforge is the same as Miniconda except it just uses the conda-forge channel by default, why create a whole different installer - why not just use miniconda and add conda-forge as the first channel to use in ~/.condarc?" 
(This is from that stackoverflow page I linked above)

We should be able to answer this question, I guess.

**Comment by hmaarrfk** [comment]
Easy of installation.

I think the readme, which currently reads:

> It is comparable to Miniconda, but with:
> * conda-forge set as the default channel
> * an emphasis on supporting various CPU architectures
> * optional support for PyPy in place of standard Python (aka "CPython")
> * optional support for Mamba in place of Conda

Can be readily changed to:

> Miniforge allows you to install the conda package manager with the following configurations pre-defined:
> * conda-forge set as the default channel
> * an emphasis on supporting various CPU architectures (aarch64, ppc64le, x86_64)
> * optional support for PyPy in place of standard Python (aka "CPython")
> * optional support for Mamba in place of Conda
> * Packages in the base environment are sourced from the `conda-forge` channel.

**Comment by hmaarrfk** [comment]
I agree the value prop is low. Miniforge is really a tool to help the CIs and those wanting to install versions of "conda" that Anaconda doesn't support.

The second bullet point is the main point we sought when creating this.

For what it is worth, the work done by isuruf to port most things to Apple's M1 has been heroic and to my knowledge, not available on the default channels as of yet.
