### ISSUE TITLE
all conda command either get killed by zsh or no output!

### ISSUE THREAD

**Issue by kasrahabib** [conda-forge/miniforge#148]
I have been using ***```Conda Miniforge```*** for almost few months to accomplish my ML tasks on ***Apple Silicon Chip*** (a.k.a M1).
However, yesterday I was trying to install a package with conda (i.e., ```conda install conda-forge name-of-package```) and the moment I executed the command, the terminal returns (without any error or output) to accept new command as everything executed normally.
After a while, I switched into my virtual environment and then ***open python shell to import Tensorflow then ```zsh``` killed the python*** as you can see below:

``` bash
(mlm1-engine) mohammadkasrahabib@iste Downloads % python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:57) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
zsh: killed     python
(mlm1-engine) mohammadkasrahabib@iste Downloads % 
```
***Importing any package related to ML (sklearn, Matplotlib or etc.) will kill the python***, but it works fine I import the ordinary python packages, e.g. ```math```.

Another thing is non of the ```conda```  commands work except ```conda --version```; terminal shows that command runs without any error, but no output. You can see it bellow: 

``` bash
(mlm1-engine) mohammadkasrahabib@iste ~ % conda list
(mlm1-engine) mohammadkasrahabib@iste ~ %   
(mlm1-engine) mohammadkasrahabib@iste ~ % conda info
(mlm1-engine) mohammadkasrahabib@iste ~ %          
(mlm1-engine) mohammadkasrahabib@iste ~ % conda env list
(mlm1-engine) mohammadkasrahabib@iste ~ % 
(mlm1-engine) mohammadkasrahabib@iste ~ % conda --version
conda 4.10.0
(mlm1-engine) mohammadkasrahabib@iste ~ % 
```
And also running the commands with ```sudo``` will output that the command is killed by ```zsh```. As you can see it bellow:
``` bash
(mlm1-engine) mohammadkasrahabib@iste ~ % sudo conda env list
Password:
zsh: killed     sudo conda env list
(mlm1-engine) mohammadkasrahabib@iste ~ % 
```

Any help would be much appreciated!
Thanks in Advance!

**Comment by xhochy** [comment]
Please have a look at the output of `sudo log stream --predicate 'sender = "kernel"'` while executing a command. This sounds like one your binaries have a corrupted code signature. The name of the binary can only be found in the kernel log.

**Comment by hmaarrfk** [comment]
I think also there has been some trouble with a recent update from Apple. Reinstalling miniforge might help

**Comment by kasrahabib** [comment]
@xhochy and @hmaarrfk,

Thanks for the kind reply. I guess something was wrong with Apple Update, because I remember I had the Xcode installed and and while troubleshooting it OS asked me that Xcode is not installed; but I am not so sure.
 
About tracking the ```log stream``` I had run this command but the log was clear!

Still the cause is unknown, however I blame Apple update. I solved it by reinstalling everything.

You can close the issue if you feel to or keep it open maybe someone else faces the same thing and find a solution for it. 😁
