### ISSUE TITLE
CODEOWNER for miniforge-images

### ISSUE THREAD

**Issue by xhochy** [conda-forge/miniforge#151]
I would like to add @conda-forge/miniforge as a CODEOWNER to https://github.com/conda-forge/miniforge-images. Would that be OK with the team?

At the same time, I would put in an application to join the `miniforge` sub-team but as I haven't found a more appropriate channel for this, I'm doing this here.

**Comment by xhochy** [comment]
@conda-forge/miniforge Friendly ping, this is an issue where I ask to help / take on some of the work but need a 👍 / 👎 whether you would like that ;)

**Comment by hmaarrfk** [comment]
I'm curious as to how this is different from the anvil images?

**Comment by jakirkham** [comment]
They are images that only supply Miniforge on a newer OS (Ubuntu 20.04 currently)

**Comment by hmaarrfk** [comment]
hmmm. interesting. it is something that maybe i would actually use.

I'm for it
