### ISSUE TITLE
Envs are deleted after upgraded using homebrew

### ISSUE THREAD

**Issue by BenjaminDbb** [conda-forge/miniforge#159]
After I upgrade miniforge using homebew, the envs I create are deleted and I have to recreate them again.

**Comment by jakirkham** [comment]
Looks like this is something Homebrew is doing. Note they create [environments in a directory they own]( https://github.com/Homebrew/homebrew-cask/blob/ed2033fb3578376c3ee58a2cb459ef96fa6eb37d/Casks/miniforge.rb#L17 ) and [remove them during uninstall]( https://github.com/Homebrew/homebrew-cask/blob/ed2033fb3578376c3ee58a2cb459ef96fa6eb37d/Casks/miniforge.rb#L21 ). This issue may be better raised with Homebrew.

One other thing worth noting, Conda can [create environments anywhere]( https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#specifying-a-location-for-an-environment ). So if one creates environments outside of Homebrew controlled paths (like in one's home directory), these should stick around after the Homebrew uninstall.

**Comment by BenjaminDbb** [comment]
Thank you, I will change the envs' directory.

**Comment by isuruf** [comment]
You can also add
```
envs_dirs:
  - ~/.conda-envs
```
to `$HOME/.condarc` and the envs will be created there.

**Comment by hmaarrfk** [comment]
I think this is something specific with how homebrew is packaging conda. As it was mentioned above, it is probably best to contact them to see how best to address this.

With the alternatives provided, I think we can close this.
