### ISSUE TITLE
M1 Macbook Air install miniforge, can't use conda 

### ISSUE THREAD

**Issue by fmbao** [conda-forge/miniforge#161]
I  install miniforge sucessfully, However, no conda init info be found in ~/.zshrc. So I can't use conda. It's so strange.

**Comment by hmaarrfk** [comment]
https://stackoverflow.com/questions/31615322/zsh-conda-pip-installs-command-not-found

might help

**Comment by fmbao** [comment]
> https://stackoverflow.com/questions/31615322/zsh-conda-pip-installs-command-not-found
> 
> might help

Thank you so much
