### ISSUE TITLE
Can not create Python3.6 environment in MacBook Air M1

### ISSUE THREAD

**Issue by PamixSun** [conda-forge/miniforge#162]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I have installed the miniforge(arm64 version) in a MacBook Air M1. When I'm trying to create a virtual environment with python3.6, it raises an error as shown below:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.6.0

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

How can I gonna fix this issue? 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
Only Python 3.8+ is supported on native ARM64. If you need Python 3.6, you will have to install a x86 miniforge and create an environment using that (and Rosetta 2).
