### ISSUE TITLE
Winget package submission

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/miniforge#163]
I've created a winget manifest for the latest Miniforge3 installer: https://github.com/microsoft/winget-pkgs/pull/16674.

winget is the new Microsoft-provided package manager for Windows. This will allow people to install miniforge via that package manager, as requested in https://github.com/conda-forge/miniforge/issues/99 (for example).

I assume this is OK. If it's not OK, then I'm happy to withdraw the PR. Otherwise, can you check that the information is OK, please?

One thing is that I changed the version number from "4.10.1-4" to "4.10.1.4" in order to match semver. Do you have a view on this?

**Comment by jakirkham** [comment]
My guess is this is ok if you plan to maintain that

**Comment by jamesmyatt** [comment]
I can maintain it, but I think the idea is that anyone can maintain it this way.

**Comment by jamesmyatt** [comment]
That makes sense. All it does is download the existing installer and run it, so there shouldn't be any significant new issues. I can certainly help if the right version isn't available.

**Comment by hmaarrfk** [comment]
> so there shouldn't be any significant new issues. 

famous last words!

**Comment by hmaarrfk** [comment]
I think we can close this now.

If you think it is important that we document the availability of this package through winget, please submit a PR adding a note to the readme.

**Comment by hmaarrfk** [comment]
See meta-issue https://github.com/conda-forge/miniforge/issues/99

**Comment by denelon** [comment]
Another option is to use the Windows Package Manager Manifest creator to automate updating the manifests with GitHub releases. https://github.com/microsoft/winget-create. There are examples of GitHub actions creating the manifest and submitting the PR.

**Comment by matterhorn103** [comment]
Hi, quick question on this – does installing via winget just download the installer, meaning the user is still required to manually execute the installer, or does it actually install and setup conda similar to described in the readme under "non-interactive install"?

**Comment by jamesmyatt** [comment]
It's essentially the same as the non-interactive install.

**Comment by skjerns** [comment]
I is possible to select installer options? e.g. adding python/conda to path?
