### ISSUE TITLE
M1 Mac Kills Miniforge3 Conda Commands

### ISSUE THREAD

**Issue by Maxgamill** [conda-forge/miniforge#197]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: After installing the arm64 version of miniforge3 and following instructions to run the .sh script with bash, choosing the option to initialise conda results in "killed 9" (seen in installation section below) as does any other conda command (seen below). Running on MacOS BigSur 11.2.3.

Adding <code>export PATH="/Users/<user>/miniforge3/condabin:${PATH}"</code> in the .zshrc and .bashrc files and running as bash or zsh still results in "Killed 9".

which conda points to: /Users/<user>/miniforge3/condabin/conda so it seems like it's finding it correctly.

I've seen on another post that running logging streams via <code>sudo log stream --predicate 'sender = "kernel”’</code> could help which I've put the output below:
2021-08-06 11:45:12.986331+0100 0x16c4c7   Default     0x0                  0      0    kernel: ignoring detached code signature on 'python3.9' with cdhash 'd959ccf0b1b8e3ec5c79f108ed727bc6c66f9cd3' because it is invalid, or not a simple adhoc signature.
2021-08-06 11:45:12.986629+0100 0x16c4c8   Default     0x0                  0      0    kernel: CODE SIGNING: process 78602[python3.9]: rejecting invalid page at address 0x100104000 from offset 0x0 in file "/Users/<user>/miniforge3/bin/python3.9" (cs_mtime:1628157278.875023080 == mtime:1628157278.875023080) (signed:1 validated:1 tainted:1 nx:0 wpmapped:0 dirty:0 depth:0)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
zsh: killed     conda list
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
zsh: killed     conda info
```
</details>

<br/>
Installation (<code>bash ~/Downloads/Miniforge.sh</code>):
<details>

```
Do you wish the installer to initialize Miniforge3
by running conda init? [yes|no]
[no] >>> yes
Downloads/Miniforge3.sh: line 455: 79203 Killed: 9               $PREFIX/bin/conda init zsh
If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false
```
or in bash
```
Do you wish the installer to initialize Miniforge3
by running conda init? [yes|no]
[no] >>> yes
Downloads/Miniforge3.sh: line 455: 79825 Killed: 9               $PREFIX/bin/conda init
If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false
```
</details>

<br/>

**Comment by rgommers** [comment]
Duplicate of gh-190 I believe. See if installing XCode fixes it.

**Comment by Maxgamill** [comment]
Apologies, I thought I had already installed it when troubleshooting this issue.

It's now working thank you so much!
