### ISSUE TITLE
Is it possible to create a macports port for apple sillicon?

### ISSUE THREAD

**Issue by khanhcsc** [conda-forge/miniforge#198]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

As the title, I found it would be much easier to maintain the package using a package manager.

**Comment by hmaarrfk** [comment]
honestly, we are pretty swamped already. if you want to contribute to macports, we can probably include it in the readme.
