### ISSUE TITLE
Provide automated miniforge docker images

### ISSUE THREAD

**Issue by yuvipanda** [conda-forge/miniforge#20]
First, *love* this project. I often end up installing miniconda, and then immediately creating a new env with conda-forge. Happy to see an alternative.

It would be very helpful if we can provide minimal miniforge docker images, similar to https://hub.docker.com/r/continuumio/miniconda3. Having it set up with conda-forge by default will make many lives easier.

We can keep it similar to the [miniconda Dockerfile](https://hub.docker.com/r/continuumio/miniconda3/dockerfile), although I'd like a few changes:

1. Pin the base image, rather than using `debian:latest`. This makes it impossible to know *which* debian version it is actually on, since that depends on what the latest version was when the image was built.
2. Use ubuntu as a base image, rather than debian. This is purely based on popularity in the community. However, this isn't a blocker. We can also easily make debian & ubuntu variants if folks need.
3. Leave $HOME clean, relying only on changes in /etc for profiles. $HOME is often mounted over with users' home directories, and this erases the changes made in $HOME/.bashrc. We could put it in /etc/profile.d instead for better effect.

This should be a completely automated process, and be built whenever a release is tagged. Providing just python3 images is probably good enough for now?

**Comment by scopatz** [comment]
Thanks @yuvipanda! I thought that the https://github.com/conda-forge/docker-images/blob/master/linux-anvil-comp7/Dockerfile is basically this/could be basically this. CC @isuruf @jakirkham

**Comment by hmaarrfk** [comment]
Conda is meant to be installed in the home directory. At least so I think.

How do you propose getting aroundthat?

**Comment by scopatz** [comment]
Conda doesn't need to be installed in the home directory.  A lot of the docker images install it into `/opt`

**Comment by yuvipanda** [comment]
@scopatz something like that, but hopefully much more minimal.

**Comment by scopatz** [comment]
I think we are very open to having something in this realm!

**Comment by yuvipanda** [comment]
@scopatz I have a PR ready at https://github.com/conda-forge/docker-images/pull/129. I actually don't know if that is the right place for it - it might make more sense for it to live in this repo, so we can auto push images on tagging. What do you think?

**Comment by scopatz** [comment]
docker-images is probably the right place.  We can always move it here, later if we decide

**Comment by jakirkham** [comment]
Anything else to do here or is this resolved with PR ( https://github.com/conda-forge/docker-images/pull/129 )?

**Comment by yuvipanda** [comment]
@jakirkham not sure if it is getting auto tagged and pushed.

**Comment by jakirkham** [comment]
Did it get added to `.travis.yml`?

**Comment by jakirkham** [comment]
For context, @yuvipanda, adding [a matrix case to `.travis.yml`]( https://github.com/conda-forge/docker-images/blob/fe1a5326926fd75bb90bfa7bfe9e39e6509ab9f1/.travis.yml#L5-L8 ) should be all that is needed.

**Comment by maresb** [comment]
As an external observer, it wasn't clear to me at first glance whether or not a Dockerfile exists yet.

Answer: Yes it exists. Here is the [Dockerfile](https://github.com/conda-forge/docker-images/blob/fe1a5326926fd75bb90bfa7bfe9e39e6509ab9f1/miniforge3/Dockerfile). There also seems to be [something on DockerHub](https://hub.docker.com/r/condaforge/miniforge3/tags) which seems to be updated too frequently and only tagged with `latest`.

**Comment by isuruf** [comment]
There's a docker file now
