### ISSUE TITLE
Comparison with miniconda and pkgs/ directory

### ISSUE THREAD

**Issue by scottyhq** [conda-forge/miniforge#21]
This project is great! I just did a few tests to compare against the miniconda installation I'm used to and noticed a subtle difference. 

Installing on ubuntu seems to automatically run a `conda clean` command removing the pkgs/ directory. This directory sticks around if installing the base environment with miniconda. It would be nice to keep it around because there are space-saving implications for hardlinks when new environments are installed (see https://github.com/conda/conda/issues/4881#issuecomment-294902365)

```
(base) ubuntu@4249f73bc693:~$ ls miniforge3/
LICENSE.txt  bin  compiler_compat  conda-meta  condabin  envs  etc  include  lib  man  share  shell  ssl  x86_64-conda_cos6-linux-gnu
(base) ubuntu@dd1c6a601f90:~$ du -sh miniforge3/
218M    miniforge3/
---------------------------------------
(base) ubuntu@59f6cde78c20:~$ du -sh miniconda3/
290M	miniconda3/
(base) ubuntu@59f6cde78c20:~$ ls miniconda3/
LICENSE.txt  bin  compiler_compat  conda-meta  condabin  envs  etc  include  lib  pkgs  share  shell  ssl  x86_64-conda_cos6-linux-gnu
```

More details here:
https://github.com/scottyhq/miniforge-test

**Comment by isuruf** [comment]
PRs welcome to add something like https://github.com/conda/constructor/blob/67d975657683f1e27482e12197c63c91f2327934/examples/grin/construct.yaml#L30

**Comment by hmaarrfk** [comment]
Why would we want to keep the old packages that were used to make miniforge.

I think it is just wasting people's bandwidth. The packages are pretty much guaranteed to be out of date right?

**Comment by scopatz** [comment]
Yeah I think that PRs are welcome here

**Comment by isuruf** [comment]
@hmaarrfk, these are hardlinks, so there's no space issue.

**Comment by scottyhq** [comment]
Thanks for the replies! After a little more thought I think this is more of a conda issue (so I can move to a different issue tracker). The use-case is installing additional conda environments and re-using as many libraries as possible to minimize disk space. Consider re-using the same python build as what miniforge currently ships in 4.8.2-1 - `python=3.7.6=h357f687_2` (also tested with simply cloning the base environment (`conda create --name myclone --clone base`):

1) **Whether or not pkgs/ exists from the (base) install, the first additional env seems to copy many things**. the second environment makes more use of links:
```
conda create -n myenv1 python=3.7.6=h357f687_2
conda create -n myenv2 python=3.7.6=h357f687_2
conda clean -yaf
(base) ubuntu@1cd8fb26ad40:~$ du -sh miniforge3/envs/*
201M	miniforge3/envs/myenv1
82M	miniforge3/envs/myenv2
```

2) If pkgs/ removed between environment installs, each env/ is approximately the same size as the (base) env:
```
conda create -n myenv1 python=3.7.6=h357f687_2
conda clean -yaf
conda create -n myenv2 python=3.7.6=h357f687_2
conda clean -yaf
(base) ubuntu@f1c0752d5782:~$ du -sh miniforge3/envs/*
201M	miniforge3/envs/myenv1
201M	miniforge3/envs/myenv2
```

**Comment by jakirkham** [comment]
Is this now addressed with PR ( https://github.com/conda-forge/miniforge/pull/31 )?

**Comment by hmaarrfk** [comment]
I think this was.

Please request to reopen if you don't think it was.
