### ISSUE TITLE
Windows installer file not found

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/miniforge#212]
I ran into an issue where attempting to download the miniforge installer on Windows (e.g. using https://github.com/conda-forge/miniforge/releases/download/4.10.3-5/Miniforge3-Windows-x86_64.exe) ran into `Error: Unexpected HTTP response: 403` as seen in [this CI build](https://github.com/coiled/dask-bigquery/runs/3657288767). Interestingly the Mambaforge version of the installer (e.g. https://github.com/conda-forge/miniforge/releases/download/4.10.3-5/Mambaforge-Windows-x86_64.exe) downloads as expected.

Not totally sure if this is just an upstream issue with GitHub, but thought it was worth reporting regardless

**Comment by jakirkham** [comment]
HTTP errors do happen periodically. Not entirely sure what we can do about them here. Did you try rerunning?

**Comment by jrbourbeau** [comment]
Just tried again and everything is working -- apologies for the noise

**Comment by jakirkham** [comment]
No worries. Thanks for the update 🙂
