### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by slerman12** [conda-forge/miniforge#216]
I installed this a long while back when I first got my M1 MacBook. I'd like to update it now without losing any of my conda envs. Is there a way I can quickly do this?

**Comment by slerman12** [comment]
`conda update conda` worked fine, but I tried:
`conda update conda-build`
And it gave this error:
```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/samlerman/code/miniforge3
  package name: conda-build
```

**Comment by hmaarrfk** [comment]
```
conda install conda-build
```

and why not use
```
mamba update --all --yes
```
