### ISSUE TITLE
failing to install packages with aarch64 on Ubuntu in termux

### ISSUE THREAD

**Issue by heungson** [conda-forge/miniforge#217]
I am trying to setup my python development environment in Samsung Galaxy Tab S7+. I am doing this just for fun. I installed termux and ubuntu 20.04. I was able to install miniforge which installed python 3.9 by default. However whenever I install packages, most packages are not properly extracted.

Packages automatically installed when I installed miniforge are ok. But after that everything is not ok. For example, after I install matplotlib, 'ls' doesn't even properly show the installed file information.
```
ls: cannot access 'libpng16-config': Operation not permitted                              
ls: cannot access 'freetype-config': Operation not permitted                              
ls: cannot access 'f2py': Operation not permitted                                         
ls: cannot access 'f2py3': Operation not permitted                                        
ls: cannot access 'f2py3.9': Operation not permitted

-rwxrwxr-x. 1 root root     154 Oct  4 11:10 conda-env                                    
-rwxrwxr-x. 1 root root     240 Oct  4 11:10 cph                                          
-rwxrwxr-x. 1 root root     278 Oct  4 11:10 deactivate                                   
-rwxrwxr-x. 2 root root   41552 Oct 31  2020 djpeg                                        l?????????? ? ?    ?          ?            ? f2py                                         
l?????????? ? ?    ?          ?            ? f2py3                                        
l?????????? ? ?    ?          ?            ? f2py3.9                                      
-rwxrwxr-x. 2 root root   24192 May 20 23:53 fax2ps                                       
-rwxrwxr-x. 2 root root   23800 May 20 23:53 fax2tiff                                     l?????????? ? ?    ?          ?            ? freetype-config
```
When I manually downloaded a conda package file and extracted files by myself with tar and bzip2, files were ok and worked fine. Python and pip not on miniforge also worked fine.

I would appreciate any help. 
Thank you.

**Comment by isuruf** [comment]
Should be fixed now. You should delete the existing miniforge installation and re-install
