### ISSUE TITLE
Release 4.10.3-6/Mambaforge-4.10.3-6-Linux-aarch64.sh is broken

### ISSUE THREAD

**Issue by combinatorylogic** [conda-forge/miniforge#218]
- [X ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Missing preconda.tar.bz2

<pre>
# bash ./getconda.sh -b -p /opt/conda
PREFIX=/opt/conda
Unpacking payload ...
ERROR   Expected environment not found at prefix: /opt/conda
ERROR   Aborting.
./getconda.sh: line 365: /opt/conda/preconda.tar.bz2: No such file or directory
</pre>

**Comment by jakirkham** [comment]
Do you have permissions to create `/opt/conda`?

**Comment by jakirkham** [comment]
Unclear. Usually we advise against setting `PYTHONHOME`. The `CONDA_PREFIX` bit is interesting, but IIUC that was pointing at the same location where the install was going to happen? That seems like it shouldn't work. Perhaps we could provide a clearer error message to users in these cases?

**Comment by hmaarrfk** [comment]
I don't have a consoldiated list. But maybe we can tag issues here with "upstream".

Eventually, we can patch constructor, and i'm not sure if that is already being done for some of the PRs in flight. However, if we patch too much, then we might as well fork.

**Comment by hmaarrfk** [comment]
List created, and updated. I'm going to close this issue for now.
