### ISSUE TITLE
Installer size issues

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/miniforge#22]
Issue:

The size of the [x86_64 installer](https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-x86_64.sh) is almost double the size of the [ppc64le installer](https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-ppc64le.sh) and roughly 35 MB larger than the [miniconda linux x86_64 installer](https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Linux-x86_64.sh).

On [gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5e5ff0cfb873303e277c9281) @isuruf suggested to check the different installation for hints. Here is what I've found so far:

I did install latest of both packages, but miniforge doesn't have the pkgs folder (see #21) . The only other big difference is in the lib-folder where miniforge has 17MB more (173MB vs. 190MB). For comparison I removed the `pkgs` folder from miniconda installation. That way the installed version of Miniconda is 182MB and the Miniforge version is 200MB, so most differences are within the lib-folder.

The overall size (incl. `pgks`-folder) of miniconda is 286MB. So this seems like kind of compression issue and/or maybe this some softlink/hardlink/copy problem. 

Besides that I noticed that there are at least one `.a` file missing in miniforge (`libssl.a`) which is available in miniconda.

<br/>

**Comment by scopatz** [comment]
> Besides that I noticed that there are at least one .a file missing in miniforge (libssl.a) which is available in miniconda.

We strongly discourage the distribution of static binaries, so it is right that this file is missing.

**Comment by kmuehlbauer** [comment]
@scopatz No problem with me. But there are quite some static binaries still distributed within miniforge.

**Comment by scopatz** [comment]
Yep, we do try to figure out where they are from and remove them.

**Comment by kmuehlbauer** [comment]
@scopatz Do you have some ideas about the size issues? Why the Linux installer is that much larger?

**Comment by scopatz** [comment]
I am not sure. Is the filesize of the underlying packages that much larger on conda-forge vs main?

**Comment by kmuehlbauer** [comment]
I'll try to make a size comparison list from miniforge vs. miniconda for  better inspection.

**Comment by scopatz** [comment]
Well, it should be conda-forge vs main, rather than miniforge vs miniconda

**Comment by jakirkham** [comment]
I guess if you are able to identify where other static libraries are coming from, we can go through and remove those.
