### ISSUE TITLE
Mac M1 - nothing provides requested python

### ISSUE THREAD

**Issue by PierreFontaineCS** [conda-forge/miniforge#221]
Hi, I'm trying to install the version for mac 1 

After a few extraction I have this error : 

`Encountered problems while solving:
  - nothing provides requested python 3.9.7 h54d631c_3_cpython
  - nothing provides requested ca-certificates 2021.10.8 h4653dfc_0
  - nothing provides requested libcxx 12.0.1 h168391b_0
  - nothing provides requested libffi 3.4.2 hbdafb3b_4
  - nothing provides requested openssl 1.1.1l h3422bc3_0
  - nothing provides requested zlib 1.2.11 hee7b306_1013
  - nothing provides requested sqlite 3.36.0 h72a2b83_2
  - nothing provides requested idna 3.1 pyhd3deb0d_0
  - nothing provides requested python_abi 3.9 2_cp39
  - nothing provides requested wheel 0.37.0 pyhd8ed1ab_1
  - nothing provides requested cffi 1.14.6 py39h52b1de0_1
  - nothing provides requested pycosat 0.6.3 py39h5161555_1006
  - nothing provides requested setuptools 58.2.0 py39h2804cbe_0
  - nothing provides requested tqdm 4.62.3 pyhd8ed1ab_0
  - nothing provides requested brotlipy 0.7.0 py39h5161555_1001
  - nothing provides openssl >=1.1.1l,<1.1.2a needed by cryptography-3.4.8-py39h73257c9_0
  - nothing provides requested pip 21.3 pyhd8ed1ab_0
  - nothing provides requested requests 2.26.0 pyhd8ed1ab_0
  - package tk-8.6.11-he1e0b03_1 requires zlib >=1.2.11,<1.3.0a0, but none of the providers can be installed

ERROR   Could not solve for environment specs`

Thank's for the help !

**Comment by wolfv** [comment]
I just tried on a Mac M1 with the latest release of Miniforge and Mambaforge and it worked fine. 

Did you download the right osx-arm64 version? Which exact installer did you try to run?

**Comment by PierreFontaineCS** [comment]
I tried with this file https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh

**Comment by PierreFontaineCS** [comment]
Exactly the same
Tried : sh Mini... , bash Mini ... 
Also tried with sudo mode 

it is very strange...
