### ISSUE TITLE
Sunsetting Mambaforge

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#222]
I think when mamba was new and a little unstable we were pretty hesitant in including it as part of the "miniforge" installer.

However, nearly a year into the creation of miniforge it seems that mamba has stabilized.

Are we ready to include mamba by default in the `miniforge3` image?

Are we ready to rebrand to `miniforge` and drop the `3`?

This would seriously decrease the maintenance burden by cutting the number of builds in half.

**Comment by jakirkham** [comment]
JFYI we recently merged PR ( https://github.com/conda-forge/docker-images/pull/197 ) to use Mambaforge in the docker-images

Not to say we shouldn't discuss simplifications here. We would just want to make sure they get propagated there (and anywhere else they need to go)

**Comment by hmaarrfk** [comment]
Thanks @isuruf for chiming in.

I think your words are quite wise.

My goal is really reducing the number of artifacts they currently stand 60+ meaning we have 30+ builds.
Often, one or two of the experimental architectures will fail.

It might be best to wait until micromamba can be used and see if we can get the space savings, and the speed increase all at once.
