### ISSUE TITLE
Drop qualifier "Apple silicon builds are experimental ..."

### ISSUE THREAD

**Issue by peterjc** [conda-forge/miniforge#223]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Quoting https://github.com/conda-forge/miniforge/blob/master/README.md

> *Apple silicon builds are experimental and haven't had testing like the other platforms.*

This was added 9 months ago in #109, but perhaps this caveat can be dropped now?

**Comment by BastianZim** [comment]
Out of interest, has anyone ever contacted Apple to ask them if they'd be willing to sponsor a CI since they now even advertise conda-forge? According to the [AWS blog](https://aws.amazon.com/blogs/aws/new-use-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/), they'll be available through there and which should take care of location, scaling, etc.

**Comment by LucasZhan** [comment]
> Out of interest, has anyone ever contacted Apple to ask them if they'd be willing to sponsor a CI since they now even advertise conda-forge? According to the [AWS blog](https://aws.amazon.com/blogs/aws/new-use-mac-instances-to-build-test-macos-ios-ipados-tvos-and-watchos-apps/), Apple M1 Chip – EC2 Mac instances will be available through there which should take care of location, scaling, etc.
> 
> Edit: MacStadium is also available but they might not be as big/famous as AWS but they do provide time for OpenSource for free: https://www.macstadium.com/opensource
> 
> Edit2: Conda-forge apparently already [uses](https://www.macstadium.com/opensource/members) MacStadium already, can that not be used for the CI?

Good points of view, but I think most of the sponsorship money of apple aimed at YouTuber. Apple give developers nothing but a shit.

**Comment by hmaarrfk** [comment]
I'm going to close this issue. It seems that we will want to remove this qualifier when testing is more robust.

**Comment by hmaarrfk** [comment]
Thank you all for the input.
