### ISSUE TITLE
add commands for creating and managing x86 environments in Mac arm64

### ISSUE THREAD

**Issue by gitony0101** [conda-forge/miniforge#225]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

As a mac user just transferred from X86, there are still some applications I need to create in x86 envrionments. Here is my solution right now:

function activate {
    if [[ $1 == *i ]]; then
        conda activate $1
        conda env config vars set CONDA_SUBDIR=osx-64
        conda deactivate
    fi
    conda activate $1
    clear
}

If possible, will this command integrate to the miniforege?

Thank you!

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by venkatasg** [comment]
Related to your question, but a slightly different solution: I was curious if its possible to have 2 separate installations - miniforge for arm64 and miniconda for x86. Or perhaps mambaforge(without conda) on arm64 and miniconda(on x86)?

**Comment by hmaarrfk** [comment]
i would post these questions on the Conda or mamba source repositories. This repo only aggregates packages into an installer but it doesn't change their functionality.

**Comment by hmaarrfk** [comment]
I'm closing because this should be raised as an issue/question in the repo for other packages mentioned above.
