### ISSUE TITLE
Codesigning error trying to install Mambaforge (or Miniforge)

### ISSUE THREAD

**Issue by jbmaxwell** [conda-forge/miniforge#235]
Issue: Can't install Mambaforge (or Miniforge) on macOS 12.1 (beta 3), Xcode 12.1 (beta 2).

I hit a codesigning error on `libcxx` when trying to install either Mambaforge or Miniforge. I've tried installing both via the shell script and brew.

```
Transaction starting
Linking bzip2-1.0.8-h3422bc3_4
Linking c-ares-1.17.2-h3422bc3_0
Linking ca-certificates-2021.10.8-h4653dfc_0
Linking libcxx-12.0.1-h168391b_0
ERROR   Could not codesign executableInvalid argument
```

I'm guessing this is something to do with the macOS beta (though could be the Xcode beta, I suppose).
Any thoughts as to how I might be able to get this to install?

**Comment by chdominguez** [comment]
Did you solve it? Having the same problem on a M1 Air

**Comment by jbmaxwell** [comment]
Oh... Sorry, but I honestly don't recall what happened with this issue. I'm running miniconda3 now, so it seems like I must have taken an entirely different route.
