### ISSUE TITLE
suggestion on naming and location of default installation directory

### ISSUE THREAD

**Issue by ngam** [conda-forge/miniforge#251]
I think it may be worth considering selecting more meaningful names and a location away from home for the standard default installation. Currently, it defaults to ~/mambaforge or ~/miniforge. I personally tend to go for something like ~/.Mambaforge-MacOSX-x86_64 or ~/.Mambaforge-MacOSX-arm64 or ~/.Mambaforge-Linux-x86_64.

Just a thought. But maybe this has its downsides? Idk

---

- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
> I personally tend to go for something like ~/.Mambaforge-MacOSX-x86_64 or ~/.Mambaforge-MacOSX-arm64 or ~/.Mambaforge-Linux-x86_64.

The operating word here being "personally". It's a personal choice and I don't want to break backwards compatibility.

**Comment by hmaarrfk** [comment]
Right. This is being used in quite a few pipelines and CIs. I think people are free to create their own flavors of this to suit their needs. 

Thank you for looking out for the best of this!

**Comment by hmaarrfk** [comment]
Both of you!

**Comment by ngam** [comment]
Thanks! 

> Just a thought. But maybe this has its downsides? Idk

Turns out potentially a lot of downsides 😵‍💫
