### ISSUE TITLE
Please use mamba 0.21.1

### ISSUE THREAD

**Issue by rabernat** [conda-forge/miniforge#265]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

There was a bug in mamba release 0.21.0 which is documented here: https://github.com/mamba-org/mamba/issues/1459
We are using mamba via miniforge in our CI environment, which is now broken (https://github.com/pangeo-forge/pangeo-forge-recipes/issues/283).

The mamba bug was fixed in release 0.21.1 (3 days ago).

I see miniforge recently updated the mamba version to 0.21.0 (https://github.com/conda-forge/miniforge/commit/ebb4deef8d1fe9929ee4f842073ae4f6ecfdb239). I would ask that you now update to 0.21.1.

Thanks for all of your hard work on this incredibly useful tool! 🙌

**Comment by wolfv** [comment]
New release of mambaforge is published. Fingers crossed!
