### ISSUE TITLE
PyPy 3.8

### ISSUE THREAD

**Issue by mach881040** [conda-forge/miniforge#274]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Can we get automated builds for PyPy, and an updated build supporting PyPy 3.8?

### Installed packages

```shell
none
```

### Environment info

```shell
none
```

**Comment by hmaarrfk** [comment]
Pypy3.8 needs to be more built out first.

https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2089
