### ISSUE TITLE
miniforge have not python.h in include 

### ISSUE THREAD

**Issue by qiniuweihe** [conda-forge/miniforge#278]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

as title

### Installed packages

```shell
none
```

### Environment info

```shell
none
```

**Comment by hmaarrfk** [comment]
please provide the requested information.

We use miniforge everyday at  conda-forge to compile programs with "python.h"

it is likely located in `include/python3.9`.

**Comment by hmaarrfk** [comment]
I've closed the issue to allow you to open a new one, going through each section one at a time.
