### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by s-m-e** [conda-forge/miniforge#28]
Issue: None.

Comment: This project is amazing! Thanks.

Question: Is support for Windows considered and/or anywhere in sight?

**Comment by hmaarrfk** [comment]
With windows we need to depend on defaults.

I'm not opposed to it, but somebody interested would have to build up the infrastructure. Potentially on azure.

You could make a PR and link to your private repo where you have the CIs running.

**Comment by isuruf** [comment]
I don't think it makes sense to have a windows installer when we need to depend on defaults channel.

**Comment by hmaarrfk** [comment]
I think adding the conda-forge channel is a large barrier as more and more projects are starting to depend on the larger python ecosystem available through conda forge.

I know for my team, teaching new joiners about conda forge is a hurdle.

I can see alot of valuein that one line being made available through the installer.

That said, this is kinda Microsoft's fault for making projects like this harder for their users.

**Comment by s-m-e** [comment]
@hmaarrfk Thanks for the info. Just so I understand you right:

> With windows we need to depend on defaults.

With "default" you mean Anaconda's original channel?

> I'm not opposed to it, but somebody interested would have to build up the infrastructure. Potentially on azure.

So if I wanted to build something like this, the constraint is not so much a technical one but the fact that I would need to build on an actual Windows system (i.e. lack of cross-platform-build capability)?

@isuruf 

> I don't think it makes sense to have a windows installer when we need to depend on defaults channel.

It depends on the use case. I am investigating the option (from a pure technical point right now) of bundling a custom set of conda-forge packages (plus conda itself) into an *offline* installer targeting Windows. Modifying Miniconda is strictly speaking an option - but as it appears a rather complicated one.

**Comment by isuruf** [comment]
> So if I wanted to build something like this, the constraint is not so much a technical one but the fact that I would need to build on an actual Windows system (i.e. lack of cross-platform-build capability)?

No. AFAIK, you can't redistribute packages in the `"defaults" channel. (Yes, it's the anaconda inc's channel)

**Comment by s-m-e** [comment]
So we're talking about a license issue?

**Comment by isuruf** [comment]
Yes. It depends on your "custom set of conda-forge" packages. Some depend on "defaults", some do not.

**Comment by hmaarrfk** [comment]
We wouldn't be shipping any compilers though, just outputs of compilers. I think we are ok on a licensing point.

**Comment by isuruf** [comment]
I wasn't talking about compilers. Some packages on windows depend on packages from defaults and we can't ship any defaults package.

**Comment by hmaarrfk** [comment]
So if we create miniforge, without any packages from defaults, but add the channel, that would be ok?

**Comment by isuruf** [comment]
Yes

**Comment by jakirkham** [comment]
What packages would we depend on from `defaults` that we couldn't distribute?

**Comment by hmaarrfk** [comment]
Cool, thanks for clearing that up.

I guess at this stage a PR would be welcome to see how far we can get, and to see what packages we would have to work around.

**Comment by isuruf** [comment]
> What packages would we depend on from defaults that we couldn't distribute?

Any package from defaults.

**Comment by jakirkham** [comment]
Sorry let me clarify. Could you please provide a list of things that the Miniforge install absolutely needs to function that would necessarily come from `defaults`?

**Comment by isuruf** [comment]
Nope. You'll have to do that yourself.

**Comment by jakirkham** [comment]
Right my understanding from having done this in the past is there are not any. So I'm asking because I'm a bit surprised to hear about this problem. Assuming someone here already investigated. Is that not the case?

**Comment by hmaarrfk** [comment]
@jakirkham that is my ubderstand too.

I mean at this stage it is a CI and recipe problem.  I think @isuruf made their point, and if we can show that there isn't such a package included (on a CI build) we are probably OK to merge.

I've been kinda stuck building old graphics related software, so my free time is rather tied.

**Comment by isuruf** [comment]
> Is that not the case?

It's not. We added vs2015_runtime only a few weeks ago.

I'm against adding `defaults` as a channel though. If we add it now and then try to change it later, people will complain. So, it's better to not add it now.

**Comment by jakirkham** [comment]
We've had that since 2016. Maybe I'm not following what was being added?

I don't have any strong feelings here. Just trying to unblock the issue. Sounds like we have done that.

@s-m-e, if this is interesting to you, would suggest starting on a PR and we can see where things go from there 🙂

**Comment by isuruf** [comment]
> We've had that since 2016. Maybe I'm not following what was being added?

That's an outdated version that was not being used at all by windows packages because the version was too low until a few weeks ago.

**Comment by isuruf** [comment]
Before starting a PR, we should decide on whether it's useful. Otherwise, there's no point asking @s-m-e to work on it.

In my opinion, it's not useful, because the 2 options we have are both not very attractive.

1. Not add defaults as a channel - Without building msys2 packages and a Fortran compiler, there's very little that miniforge can install without the user adding defaults. This might change in the future though.

2. Add defaults as a channel - This is different from all the other platforms that we support and I think Miniforge shouldn't do this for win. Miniforge is different because it doesn't use "defaults" by default. Otherwise it's almost the same as miniconda with conda-forge channel added. Also, if we add it now, then we'll have to keep it forever because people will complain.

**Comment by s-m-e** [comment]
> Before starting a PR, we should decide on whether it's useful. Otherwise, there's no point asking @s-m-e to work on it.

Just exploring the options at this point - I want to be sure I understand the subject matter properly.

> In my opinion, it's not useful, because the 2 options we have are both not very attractive.

Hmm depends on the use case. You are missing an important use-case in my opinion: `miniforge` as a basis for custom (Windows) installers (with or without defaults - depending on the solution of licensing issues - though really targeting the "without" option).

>     1. Not add defaults as a channel - Without building msys2 packages and a Fortran compiler, there's very little that miniforge can install without the user adding defaults. This might change in the future though.

Let's assume that adding defaults if **off** the table, i.e. it is not supposed to happen. So again just to be clear: On Windows, the "limitation" at this point is the lack of a working Fotran compiler and msys2 within the conda-forge ecosystem? That's "all"? So if those would exist, `miniforge` could exist for Windows in a meaningful way without touching defaults at all?

>     2. Add defaults as a channel [...]

See above - not what I am interested in at the moment ;)

**Comment by isuruf** [comment]
> So again just to be clear: On Windows, the "limitation" at this point is the lack of a working Fotran compiler and msys2 within the conda-forge ecosystem? That's "all"? So if those would exist, miniforge could exist for Windows in a meaningful way without touching defaults at all?

That's "all" is an oversimplification, but sure, let's go with that's all.

**Comment by s-m-e** [comment]
@isuruf I am aware that it is oversimplified :) Again, just trying to understand the constraints ...

Digging even further into this: Have those two issues ever been touched before (as in "attempted" to be solved, even if incomplete or not entirely working) or is this completely new territory for conda-forge?

**Comment by isuruf** [comment]
https://github.com/conda-forge/scipy-feedstock/issues/80
https://github.com/conda-forge/conda-forge.github.io/issues/1044

**Comment by scopatz** [comment]
For what it is worth, I am 100% in favor of having a miniforge windows distribution and that should be one of the goals of miniforge

**Comment by isuruf** [comment]
If we are going to add a windows distribution with defaults added as a channel, I'm okay with that as long as the name is different. I'd like `miniforge` to mean only conda-forge.

**Comment by scopatz** [comment]
I don't think that makes sense to split the branding like that. We can build up to being conda-forge only, but I think it is harder to build up if we don't have anything to start with

**Comment by isuruf** [comment]
We are already conda-forge only on linux and osx. As I said earlier, adding `defaults` now and removing it when we are ready is going to cause breakage and confusion.

**Comment by scopatz** [comment]
I thought on windows we are mostly relying on msys2 now, not defaults. I guess my question is at this point can we build an installer without defaults? I bet we are pretty close.

**Comment by isuruf** [comment]
`defaults` is an aggregate channel. See also my comment at https://github.com/conda-forge/miniforge/issues/28#issuecomment-623852355

**Comment by isuruf** [comment]
> I guess my question is at this point can we build an installer without defaults? I bet we are pretty close.

You are asking the same question as https://github.com/conda-forge/miniforge/issues/28#issuecomment-623846409 and my answer is the same. Please read the whole thread when you have time.

**Comment by scopatz** [comment]
Yeah - sorry, I don't have time right now.

**Comment by jakirkham** [comment]
The main advantage of a Windows installer ( at least as originally conceived https://github.com/conda-forge/staged-recipes/issues/610#issuecomment-227273497 ) would be to speed up CI. Today we spend ~4mins just doing setup and updating packages in the `base` environment. Being able to cut that down significantly would be a real productivity boost.

**Comment by isuruf** [comment]
Please do some research before you comment. Here's what I did.

1. I created a new environment with conda-forge dependencies.

2. Re-ran the command for installing our additional dependencies that wouldn't come with miniforge. [See log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/179543/logs/52) (3 min 7s)

3. Checked how much time it would take to install miniconda on windows. [See log](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/179549/logs/46) (1 min 4s)

So there's no advantage at all.

**Comment by isuruf** [comment]
Now that a number of packages like `MKL` and `scipy` are included in conda-forge, I published a windows installer with only `conda-forge` and msys2. See https://github.com/conda-forge/miniforge#download

**Comment by jakirkham** [comment]
Thanks so much for doing this Isuru! 😄

**Comment by jamesmyatt** [comment]
Thanks @isuruf ❤️
