### ISSUE TITLE
I installed Miniforge but its opting Miniconda by default. how to solve this?

### ISSUE THREAD

**Issue by Rishabh951** [conda-forge/miniforge#289]
### Additional comment:

miniforge was successfully installed!
(base) rishabhsrivastava@Rishabhs-Air ~ % which python
/opt/miniconda3/bin/python

**Comment by jakirkham** [comment]
Probably there is still something in `~/.bash_profile` or equivalent that is activating Miniconda. Would need to get rid of that and use something equivalent to activate Miniforge

**Comment by hmaarrfk** [comment]
you also need to close and reopen your terminal for things to take effect.

**Comment by isuruf** [comment]
@Rishabh951, please re-open if this doesn't answer your question.
