### ISSUE TITLE
Enable feedstocks to provide minimal installers?

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/miniforge#29]
I recently created a feedstock conda-forge/verilator-feedstock.  [Verilator](https://www.veripool.org/projects/verilator/wiki/Intro) is used widely in my industry (semiconductor R&D) and there may be people who are interested in having a shell or dpkg installer for only Verilator and not needing to enable conda.

Could conda-smithy be taught to render something (perhaps a separate github-action) that creates installers and publishes them as 'releases' on the feedstock like miniforge does?  Would it be worth doing that?  Perhaps I should have filed this under conda-smithy...

**Comment by hmaarrfk** [comment]
Not too sure if this is the best place for this discussion.

Maybe post it on conda-smitgy?

**Comment by scopatz** [comment]
Yeah - this is maybe a smithy or constructor thing.

**Comment by scopatz** [comment]
I am not sure where we would shove the installers once they are built

**Comment by timsnyder** [comment]
I was thinking that we'd do the same thing that miniforge does and put them in release artifacts on github.

**Comment by timsnyder** [comment]
I guess github calls them Assets, not artifacts: https://github.com/conda-forge/miniforge/releases

**Comment by scopatz** [comment]
We do that for miniforge because it is a relatively small size for the assests.  I think if we started doing this for many packages we would exceed a lot of hard & soft limits that github has.  It is easy to see many installers getting to the GB level.

**Comment by timsnyder** [comment]
Makes sense.  I think we can say that this isn't a good idea because of the limits on GitHub storage.
