### ISSUE TITLE
Create  both, x86_64 and arm64 environments on OSX, at the same time

### ISSUE THREAD

**Issue by pya** [conda-forge/miniforge#290]
### Comment:

I transferred many conda environments form my old Macbook to an M1 machine. They work but use the x86_64  version.
I would like to **keep** all these environments. At the same time I would like to create new environments with an arm64 interpreter. What would be the best way to do this?

Currently, I use mamba, which is installed in `/Users/<user>/miniconda3/bin/mamba`.
In addition, I would like to install mambaforge for the arm64 version.
Would this work? I guess I would get two `mamba` commands. Could I use both of them at the same time? Is just defining an alias for one of the `mamba` commands sufficient?

**Comment by lexust1** [comment]
I had a similar question several days ago. I used Anaconda3 before I need TensorFlow that supports the M1 processor. So, I installed Miniforge3 that can install TensorFlow for arm64 processors. Now it is possible to use Anaconda3 and Miniforge3 at the same time. 
 
Every conda distribution creates own environments, libraries, packages, etc. The only thing that you need is to change the the .zshrc-file to choose the conda distribution. I use a little script that simplifies this process. 

1. Add the line in your .zshrc-file:
`alias chconda='bash ~/chconda.sh ~/.zshrc; source ~/.zshrc`

2. Create a script chconda.sh at the same folder where the .zshrs-file is located:
`echo "Enter the name of conda distribution (an for Anaconda3 OR mf for Miniforge3):"
read -p "[an OR mf] = " conda_ver

if [[ $conda_ver == "an" ]]; then
    sed -i '' "s/miniforge3/anaconda3/gi" $1
    echo "Anaconda3 is initialized."
elif [[ $conda_ver == "mf" ]]; then
    sed -i '' "s/anaconda3/miniforge3/gi" $1
    echo "Miniforge3 is initialized."
else
    echo "$conda_ver is not a valid name, try an or mf"
fi`

3. Use command chconda to choose your conda distribution.

There is a good video that explains how to use different conda distributions in parallel:
[https://www.youtube.com/watch?v=w2qlou7n7MA](url)

**Comment by pya** [comment]
There is an easy solution: Just use [`CONDA_SUBDIR`](https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple)

**Comment by pya** [comment]
There is an easy solution: Just use [`CONDA_SUBDIR`](https://stackoverflow.com/questions/65415996/how-to-specify-the-architecture-or-platform-for-a-new-conda-environment-apple)
