### ISSUE TITLE
Installation fails on Ubuntu 20.04.4 x86_64 because of missing ncurses

### ISSUE THREAD

**Issue by rohel01** [conda-forge/miniforge#293]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello,

Using the linux install script for Miniforge3 4.12.0-0, installation fails after unpacking the payload due to unsolvable environment.
The error is:

```
Encountered problems while solving:
  - nothing provides ncurses >=6.2,<6.3.0a0 needed by readline-8.1-h46c0cb4_0
# ... Repeated many times...
  - nothing provides ncurses >=6.2,<6.3.0a0 needed by readline-8.1-h46c0cb4_0

The environment can't be solved, aborting the operation
error    Could not solve for environment specs
critical UnsatisfiableError

```

Full log of the terminal sessions:
[logs.txt](https://github.com/conda-forge/miniforge/files/8488223/logs.txt)

Kind regards,

### Installed packages

```shell
None since installation fails
```

### Environment info

```shell
Ubuntu 20.04.4 LTS
Miniforge3 4.12.0-0
```

**Comment by rohel01** [comment]
Looking at the logs, it seems ncurses-6.3 is automatically extracted, but this version is incompatible with readline-8.1 requirements

```
Extracting "ncurses-6.3-h9c3ff4c_0.tar.bz2"

  - nothing provides ncurses >=6.2,<6.3.0a0 needed by readline-8.1-h46c0cb4_0

```

FYI, installing for the 4.11.0-4 script installer fails for a similar reason.

**Comment by hmaarrfk** [comment]
Are you already in an other conda environment? 

Does the folder `${HOME}/miniforge3` already exist? These are two known issues that have stuck around for a while unfortunately.

**Comment by hmaarrfk** [comment]
I tried to install Miniforge3 (from within an other existing environment) and it seemed to work ok.

**Comment by hmaarrfk** [comment]
In your specific case, does hte folder `/home/melchiore/utils/miniforge3` exist prior to the installation?

**Comment by rohel01** [comment]
I have minconda installed. So I cleaned my `.bashrc` before launching the terminal from which I performed the miniforge install.

The `miniforge3` directory did not exist at the time of the first install. For my second attempt, I remeber the script complained it was already existing so I deleted it manually.

I you have a list of pre-conditions you want me to check before making another attempt, I will try.

**Comment by rohel01** [comment]
Here are the [logs.txt](https://github.com/conda-forge/miniforge/files/8510866/logs.txt)  of another attempt:

- Clean environment (conda executable not found)
- `/home/melchiore/utils/miniforge3` deleted prior to making the attempt

**Comment by hmaarrfk** [comment]
The only thing I can think of is if you have a `.condarc` file in your home directory. Can you remove that file

**Comment by rohel01** [comment]
Yes, I did have a `.condarc`  file in my home directory and removing it solved the issue.
Thank you!
