### ISSUE TITLE
Docs mention that RasbianOS is unsupported, but miniforge works on the RasbianOS full 64bit

### ISSUE THREAD

**Issue by MarximusMaximus** [conda-forge/miniforge#309]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Currently the docs state:

> (**) While the Raspberry PI includes a 64 bit processor, the [RasbianOS](https://www.raspberrypi.org/software/operating-systems/) is built on a 32 bit kernel and is not a supported configuration for these installers. We recommend using a 64 bit linux distribution such as [Ubuntu for Raspberry PI](https://ubuntu.com/raspberry-pi).

However, RaspbianOS is now available in a full 64-bit version (with 64-bit kernel), and reports `uname` as "Linux" and `uname -m` as "aarch64". The docs probably should be updated to note that only RaspbianOS full 64-bit version is support but the mixed bit/32-bit version is not. (See https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit ).

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by hmaarrfk** [comment]
Thanks for bringing this up again. A PR welcome to update the language.
