### ISSUE TITLE
My computer is M1，use the Anaconda 4.13.0

### ISSUE THREAD

**Issue by LowrenceHo** [conda-forge/miniforge#319]
### Comment:

My computer is M1，use the Anaconda 4.13.0,I found that there is no official version that can be matched

Example：
PackagesNotFoundError: The following packages are not available from current channels:

  - miniforge3-macosx-x86_64（4.12.0）
 
Could you please give me the solution to solve this problem?
thanks !

**Comment by hmaarrfk** [comment]
arm64 is the architecture behind "apple silicon" or "M1". 
![image](https://user-images.githubusercontent.com/90008/173239786-79651759-e81a-42c1-8202-2bbf32070061.png)

You can use that installer from this website.

If you are looking for something from Anaconda (the company), they have an installer that you can download from:
https://www.anaconda.com/products/distribution#Downloads

From anaconda:
![image](https://user-images.githubusercontent.com/90008/173239764-4cd12439-24fc-4271-9056-617542d7ff83.png)

**Comment by LowrenceHo** [comment]
> arm64 is the architecture behind "apple silicon" or "M1". ![image](https://user-images.githubusercontent.com/90008/173239786-79651759-e81a-42c1-8202-2bbf32070061.png)
> 
> You can use that installer from this website.
> 
> If you are looking for something from Anaconda (the company), they have an installer that you can download from: https://www.anaconda.com/products/distribution#Downloads
> 
> From anaconda: ![image](https://user-images.githubusercontent.com/90008/173239764-4cd12439-24fc-4271-9056-617542d7ff83.png)

thank you !!!
