### ISSUE TITLE
Windows WSL Ubuntu install fails with "Miniforge3-Linux-x86_64.sh: line 363: /c/Users/runneradmin/miniforge3/conda.exe: cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by MarximusMaximus** [conda-forge/miniforge#320]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

After setting up a Github runner (64bit) with Windows + WSL + Ubuntu 20.04 OR Debian (latest) and then downloading and running Miniforge3-Linux-x86_64.sh, it fails with these errors (set -x is on):

```
++ /d/a/batteries-forking-included/batteries-forking-included/bfi_temp/batteries-forking-included/downloads/Miniforge3-Linux-x86_64.sh -b -f -p /c/Users/runneradmin/opt/conda/miniforge
PREFIX=/c/Users/runneradmin/miniforge3
Unpacking payload ...
/d/a/batteries-forking-included/batteries-forking-included/bfi_temp/batteries-forking-included/downloads/Miniforge3-Linux-x86_64.sh: line 363: /c/Users/runneradmin/miniforge3/conda.exe: cannot execute binary file: Exec format error
/d/a/batteries-forking-included/batteries-forking-included/bfi_temp/batteries-forking-included/downloads/Miniforge3-Linux-x86_64.sh: line 366: /c/Users/runneradmin/miniforge3/preconda.tar.bz2: No such file or directory
```

This doesn't seem to be related to any of the 32bit versions of this error b/c everything is setup as 64bit, unless conda.exe is 32bit?

I am aware that testing on WSL doesn't happen currently. I don't know what CI you guys currently use, but I have /otherwise/ successfully setup WSL testing using Github's runners and can assist with that (if desired).

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by traversaro** [comment]
I used consistently miniforge3/mambaforge on WSL with no such problmems. Are you sure that this is not related to the fact that there is a conda/miniforge3 installation on the Windows side, and the `PATH`of WSL contains the `PATH` of the Windows side? Did you tried to set `appendWindowsPath` to false (as explained in https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) and tried again?

**Comment by MarximusMaximus** [comment]
> If you want to add a step to test against WSL and reproduce the issue, that would be appreciated.

I will fork and look into this.

> Are you sure that this is not related to the fact that there is a conda/miniforge3 installation on the Windows side, and the PATHof WSL contains the PATH of the Windows side?

I will look into this on the github runner, I think it does come with some form of conda install and perhaps it is interfering. (Although the same is true of the linux runners and it doesn't interfere.)

> Did you tried to set appendWindowsPath to false (as explained in https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) and tried again?

Unsure if I can do this in a github runner, b/c I don't think I can restart the WSL service?

**Comment by traversaro** [comment]
> > Did you tried to set appendWindowsPath to false (as explained in https://docs.microsoft.com/en-us/windows/wsl/wsl-config#interop-settings) and tried again?
> 
> Unsure if I can do this in a github runner, b/c I don't think I can restart the WSL service?

Good point, do you have an example of GitHub runner with WSL?

**Comment by hmaarrfk** [comment]
Closing as the issue seems stale. Please comment with updated information if the original issue isn't resolved.
