### ISSUE TITLE
How to upgrade the pypy version in the root env?

### ISSUE THREAD

**Issue by Ca11back** [conda-forge/miniforge#322]
### Comment:

ENV: the latest version of Mambaforge-pypy3.

I tried:
`mamba install python=3.9.12`

```
Encountered problems while solving:
  - package pypy3.7-7.3.7-hbc09475_3 has constraint python 3.7.* *_73_pypy conflicting with python-3.9.12-0_73_pypy
 ```
 
Any suggestions? Thanks

**Comment by hmaarrfk** [comment]
I think the correct command is:
```
 mamba install pypy3.9
```

however, it seems that a pinnned package already exists. Not too sure how to unpin it.

```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.24.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['pypy3.9']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.7.*


Encountered problems while solving:
  - package pypy3.9-7.3.8-h56abe6f_1 has constraint python 3.9.* *_73_pypy conflicting with python-3.7.12-0_73_pypy
```

**Comment by Ca11back** [comment]
> I think the correct command is:
> 
> ```
>  mamba install pypy3.9
> ```
> 
> however, it seems that a pinnned package already exists. Not too sure how to unpin it.
> 
> ```
> 
>                   __    __    __    __
>                  /  \  /  \  /  \  /  \
>                 /    \/    \/    \/    \
> ███████████████/  /██/  /██/  /██/  /████████████████████████
>               /  / \   / \   / \   / \  \____
>              /  /   \_/   \_/   \_/   \    o \__,
>             / _/                       \_____/  `
>             |/
>         ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
>         ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
>         ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
>         ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
>         ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
>         ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝
> 
>         mamba (0.24.0) supported by @QuantStack
> 
>         GitHub:  https://github.com/mamba-org/mamba
>         Twitter: https://twitter.com/QuantStack
> 
> █████████████████████████████████████████████████████████████
> 
> 
> Looking for: ['pypy3.9']
> 
> conda-forge/linux-64                                        Using cache
> conda-forge/noarch                                          Using cache
> 
> Pinned packages:
>   - python 3.7.*
> 
> 
> Encountered problems while solving:
>   - package pypy3.9-7.3.8-h56abe6f_1 has constraint python 3.9.* *_73_pypy conflicting with python-3.7.12-0_73_pypy
> ```

seems it is unchangeable for the root env,thanks

**Comment by hmaarrfk** [comment]
I think this is an interesting ask.

feel free to reopen
