### ISSUE TITLE
Homebrew M1 `conda update -n base conda`: The environment is inconsistent, please check the package plan carefully

### ISSUE THREAD

**Issue by nyngwang** [conda-forge/miniforge#325]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::requests==2.27.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::brotlipy==0.7.0=py39hb18efdd_1004
  - conda-forge/osx-arm64::setuptools==62.3.2=py39h2804cbe_0
  - conda-forge/noarch::six==1.16.0=pyh6c4a22f_0
  - conda-forge/noarch::charset-normalizer==2.0.12=pyhd8ed1ab_0
  - conda-forge/osx-arm64::python==3.9.13=hc596b02_0_cpython
  - conda-forge/osx-arm64::sqlite==3.38.5=h40dfcc0_0
  - conda-forge/noarch::urllib3==1.26.9=pyhd8ed1ab_0
  - conda-forge/noarch::wheel==0.37.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::readline==8.1=hedafd6a_0
  - conda-forge/osx-arm64::ruamel_yaml==0.15.80=py39h9eb174b_1007
  - conda-forge/noarch::colorama==0.4.4=pyh9f0ad1d_0
  - conda-forge/osx-arm64::cffi==1.15.0=py39h52b1de0_0
  - conda-forge/noarch::pyopenssl==22.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::tqdm==4.64.0=pyhd8ed1ab_0
  - conda-forge/noarch::pip==22.1.2=pyhd8ed1ab_0
  - conda-forge/noarch::idna==3.3=pyhd8ed1ab_0
  - conda-forge/osx-arm64::pysocks==1.7.1=py39h2804cbe_5
  - conda-forge/osx-arm64::pycosat==0.6.3=py39hb18efdd_1010
  - conda-forge/osx-arm64::cryptography==37.0.2=py39h4cb6239_0
  - conda-forge/osx-arm64::conda==4.12.0=py39h2804cbe_0
  - conda-forge/osx-arm64::python_abi==3.9=2_cp39
  - conda-forge/osx-arm64::conda-package-handling==1.8.1=py39hb18efdd_1
  - conda-forge/osx-arm64::certifi==2022.5.18.1=py39h2804cbe_0
  - conda-forge/noarch::pycparser==2.21=pyhd8ed1ab_0
done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/homebrew/Caskroom/miniforge/base

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.6.15  |       h4653dfc_0         149 KB  conda-forge
    libzlib-1.2.12             |       ha287fd2_1          48 KB  conda-forge
    openssl-1.1.1p             |       ha287fd2_0         1.8 MB  conda-forge
    zlib-1.2.12                |       ha287fd2_1          77 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.0 MB

The following packages will be UPDATED:

  ca-certificates                    2022.5.18.1-h4653dfc_0 --> 2022.6.15-h4653dfc_0
  libzlib                                 1.2.12-h90dfc92_0 --> 1.2.12-ha287fd2_1
  openssl                                 1.1.1o-ha287fd2_0 --> 1.1.1p-ha287fd2_0
  zlib                                    1.2.12-h90dfc92_0 --> 1.2.12-ha287fd2_1
```

I have accepted the update by entering `y`

### Installed packages

```shell
# packages in environment at /opt/homebrew/Caskroom/miniforge/base:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py39hb18efdd_1004    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
certifi                   2022.5.18.1      py39h2804cbe_0    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39h2804cbe_0    conda-forge
conda-package-handling    1.8.1            py39hb18efdd_1    conda-forge
cryptography              37.0.2           py39h4cb6239_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libzlib                   1.2.12               ha287fd2_1    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   1.1.1p               ha287fd2_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb18efdd_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_5    conda-forge
python                    3.9.13          hc596b02_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39h9eb174b_1007    conda-forge
setuptools                62.3.2           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               h40dfcc0_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zlib                      1.2.12               ha287fd2_1    conda-forge
```

### Environment info

```shell
active environment : None
            shell level : 0
       user config file : /Users/ningwang/.condarc
 populated config files : /opt/homebrew/Caskroom/miniforge/base/.condarc
                          /Users/ningwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __osx=12.4=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniforge/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniforge/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/homebrew/Caskroom/miniforge/base/pkgs
                          /Users/ningwang/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniforge/base/envs
                          /Users/ningwang/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.13 Darwin/21.5.0 OSX/12.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by nyngwang** [comment]
I consider the:

>  The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:`

as no harm, so I have accepted the update. But still want to make a check here.

**Comment by ustc-liu** [comment]
same problem here on my m1 mba.

**Comment by user799595** [comment]
Having the same issue unfortunately.

Completely clean install on Mambaforge (both arm64 and i386 on M1):

```
The following packages are causing the inconsistency:

  - conda-forge/noarch::requests==2.27.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::brotlipy==0.7.0=py39hb18efdd_1004
  - conda-forge/osx-arm64::setuptools==62.3.2=py39h2804cbe_0
  - conda-forge/noarch::six==1.16.0=pyh6c4a22f_0
  - conda-forge/noarch::charset-normalizer==2.0.12=pyhd8ed1ab_0
  - conda-forge/osx-arm64::python==3.9.13=hc596b02_0_cpython
  - conda-forge/osx-arm64::sqlite==3.38.5=h40dfcc0_0
  - conda-forge/osx-arm64::mamba==0.22.1=py39hde45b87_1
  - conda-forge/noarch::urllib3==1.26.9=pyhd8ed1ab_0
  - conda-forge/noarch::wheel==0.37.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::readline==8.1=hedafd6a_0
  - conda-forge/osx-arm64::ruamel_yaml==0.15.80=py39h9eb174b_1007
  - conda-forge/noarch::colorama==0.4.4=pyh9f0ad1d_0
  - conda-forge/osx-arm64::cffi==1.15.0=py39h52b1de0_0
  - conda-forge/noarch::pyopenssl==22.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::tqdm==4.64.0=pyhd8ed1ab_0
  - conda-forge/noarch::pip==22.1.2=pyhd8ed1ab_0
  - conda-forge/noarch::idna==3.3=pyhd8ed1ab_0
  - conda-forge/osx-arm64::pysocks==1.7.1=py39h2804cbe_5
  - conda-forge/osx-arm64::pycosat==0.6.3=py39hb18efdd_1010
  - conda-forge/osx-arm64::cryptography==37.0.2=py39h4cb6239_0
  - conda-forge/osx-arm64::libmambapy==0.22.1=py39h43fb93c_1
  - conda-forge/osx-arm64::conda==4.12.0=py39h2804cbe_0
  - conda-forge/osx-arm64::python_abi==3.9=2_cp39
  - conda-forge/osx-arm64::conda-package-handling==1.8.1=py39hb18efdd_1
  - conda-forge/osx-arm64::certifi==2022.5.18.1=py39h2804cbe_0
  - conda-forge/noarch::pycparser==2.21=pyhd8ed1ab_0
done
```

Jupyter is also broken...

**Comment by hmaarrfk** [comment]
Sorry for the delay. Ultimately, we aren't always able to recreate in every downstream packaged environment.

Can any of you recreate without homebrew? If not. You might get better help asking the homebrew devs directly :/

**Comment by hmaarrfk** [comment]
Thank you for pointing me to that detail.

It is, indeed odd.

**Comment by hubzado** [comment]
Looks like it is fixed now. Updated all environments.

**Comment by ustc-liu** [comment]
> Looks like it is fixed now. Updated all environments.

I still got the same issue.

**Comment by jharrang** [comment]
**There's a potential 1-line fix if using homebrew-installed `mambaforge`!**

I seemingly was just able to fix this on a 2022 M1 MBP where I encountered this from a completely clean homebrew-installed `mambaforge` install by running (in the `base` environment):
```mamba update --all```

That updated `conda` to `4.13` and `mamba` to `0.24.0`. It's possible that I'm no longer seeing the "inconsistent environment" warning by virtue of having no updateable packages, but at least for the time being this seems to have fixed things:

```
❯ conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

**Comment by nyngwang** [comment]
```zsh
✔ ~ % conda update -n base conda                                                                                                                                16:16:24
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

it seems that the problem is resolved now.

**Comment by ustc-liu** [comment]
> ```shell
> ```shell
> ✔ ~ % conda update -n base conda                                                                                                                                16:16:24
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> it seems that the problem is resolved now.
> ```

still got the errors


sheng@liu ~ % conda update -n base conda > 1.txt

The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::requests==2.27.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::brotlipy==0.7.0=py39hb18efdd_1004
  - conda-forge/osx-arm64::setuptools==62.3.2=py39h2804cbe_0
  - conda-forge/noarch::six==1.16.0=pyh6c4a22f_0
  - conda-forge/noarch::charset-normalizer==2.0.12=pyhd8ed1ab_0
  - conda-forge/osx-arm64::python==3.9.13=hc596b02_0_cpython
  - conda-forge/osx-arm64::sqlite==3.38.5=h40dfcc0_0
  - conda-forge/noarch::urllib3==1.26.9=pyhd8ed1ab_0
  - conda-forge/noarch::wheel==0.37.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::readline==8.1=hedafd6a_0
  - conda-forge/osx-arm64::ruamel_yaml==0.15.80=py39h9eb174b_1007
  - conda-forge/noarch::colorama==0.4.4=pyh9f0ad1d_0
  - conda-forge/osx-arm64::cffi==1.15.0=py39h52b1de0_0
  - conda-forge/noarch::pyopenssl==22.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::tqdm==4.64.0=pyhd8ed1ab_0
  - conda-forge/noarch::pip==22.1.2=pyhd8ed1ab_0
  - conda-forge/noarch::idna==3.3=pyhd8ed1ab_0
  - conda-forge/osx-arm64::pysocks==1.7.1=py39h2804cbe_5
  - conda-forge/osx-arm64::pycosat==0.6.3=py39hb18efdd_1010
  - conda-forge/osx-arm64::cryptography==37.0.2=py39h4cb6239_0
  - conda-forge/osx-arm64::conda==4.12.0=py39h2804cbe_0
  - conda-forge/osx-arm64::python_abi==3.9=2_cp39
  - conda-forge/osx-arm64::conda-package-handling==1.8.1=py39hb18efdd_1
  - conda-forge/osx-arm64::certifi==2022.5.18.1=py39h2804cbe_0
  - conda-forge/noarch::pycparser==2.21=pyhd8ed1ab_0


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda

**Comment by bakj1979** [comment]
Brand new M1 MBP with freshly installed Miniforge and am getting the same errors. 

**Has a solution been found (either with AND without home-brew)?**

The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/noarch::requests==2.27.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::brotlipy==0.7.0=py39hb18efdd_1004
  - conda-forge/osx-arm64::setuptools==62.3.2=py39h2804cbe_0
  - conda-forge/noarch::six==1.16.0=pyh6c4a22f_0
  - conda-forge/noarch::charset-normalizer==2.0.12=pyhd8ed1ab_0
  - conda-forge/osx-arm64::python==3.9.13=hc596b02_0_cpython
  - conda-forge/osx-arm64::sqlite==3.38.5=h40dfcc0_0
  - conda-forge/noarch::urllib3==1.26.9=pyhd8ed1ab_0
  - conda-forge/noarch::wheel==0.37.1=pyhd8ed1ab_0
  - conda-forge/osx-arm64::readline==8.1=hedafd6a_0
  - conda-forge/osx-arm64::ruamel_yaml==0.15.80=py39h9eb174b_1007
  - conda-forge/noarch::colorama==0.4.4=pyh9f0ad1d_0
  - conda-forge/osx-arm64::cffi==1.15.0=py39h52b1de0_0
  - conda-forge/noarch::pyopenssl==22.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::tqdm==4.64.0=pyhd8ed1ab_0
  - conda-forge/noarch::pip==22.1.2=pyhd8ed1ab_0
  - conda-forge/noarch::idna==3.3=pyhd8ed1ab_0
  - conda-forge/osx-arm64::pysocks==1.7.1=py39h2804cbe_5
  - conda-forge/osx-arm64::pycosat==0.6.3=py39hb18efdd_1010
  - conda-forge/osx-arm64::cryptography==37.0.2=py39h4cb6239_0
  - conda-forge/osx-arm64::conda==4.12.0=py39h2804cbe_0
  - conda-forge/osx-arm64::python_abi==3.9=2_cp39
  - conda-forge/osx-arm64::conda-package-handling==1.8.1=py39hb18efdd_1
  - conda-forge/osx-arm64::certifi==2022.5.18.1=py39h2804cbe_0
  - conda-forge/noarch::pycparser==2.21=pyhd8ed1ab_0
done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

$ conda update -n base conda

**Comment by hmaarrfk** [comment]
@ngam are you able to help here? I don't have a mac, but it seems like you might have some useful input.

**Comment by hmaarrfk** [comment]
Thanks for chiming in. I think there was some hesitancy in updating mamba though I think it has largely gone away.

Not sure why this PR has remained as a draft for so long.

https://github.com/conda-forge/miniforge/pull/301

Hopefully next week we can move on it.

**Comment by hmaarrfk** [comment]
We released a new version on miniforge. Hopefully it will get to homebrew soon and alleviate these problems

**Comment by hmaarrfk** [comment]
Thank you all for your patience. Feel free to open an issue if this comes up again. I think significant changes happened that it makes the information here somewhat stale

**Comment by cstrlln** [comment]
Hi, I installed miniforge a couple of weeks ago on and M1 and ran into the same issues described above.
As suggested tried doing a mambaforge install with brew but get this message:

Error: Cask 'mambaforge' conflicts with 'miniforge'.

Should I just try to reinstall everything?
