### ISSUE TITLE
Most conda operations fail: conda info could not be constructed.

### ISSUE THREAD

**Issue by fonnesbeck** [conda-forge/miniforge#328]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

After installing miniforge on Ubuntu Linux, I am unable to run most conda operations. For example, `conda create` or `conda install` return the following:

```
  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')
```

The actual exception is:

```
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
certifi                   2022.5.18.1      py39hf3d152e_0    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39hf3d152e_0    conda-forge
conda-package-handling    1.8.1            py39hb9d737c_1    conda-forge
cryptography              37.0.2           py39hd97740a_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb9d737c_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39hb9d737c_1007    conda-forge
setuptools                62.3.2           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zlib                      1.2.12               h166bdaf_0    conda-forge
```

### Environment info

```shell
`conda info` results in the same error as is in the report above
```

**Comment by hmaarrfk** [comment]
Might you have an old `.condarc ` file?

What does
```
ls ${HOME}/.condarc
cat ${HOME}/.condarc
```
give you?

**Comment by BrotherMarat** [comment]
Hi, i have same problem, did you fixed it?

**Comment by hmaarrfk** [comment]
sorry i didn't respond earlier (it has been nearly 2 months!).

I can't be sure that the 3 of you are experiencing the same issue.

I would prefer, if you each opened a different issue, cross referencing any issues you found that might be related.

I have a suspicion that some of you have to transition from Anaconda's repositories to conda-forge's. THis can cause some challenges.

conda-forge's channels should be listed as the top channel. with "strict channel priority" enabled. We state this in our installation instructions: https://conda-forge.org/

The anaconda->conda-forge transition can be painful. I might recommend you simply re-install. If you plan to use conda-forge, do consider our MIniforge installers.

I'm going to leave this issue open for an other 2 weeks for @fonnesbeck to reply, but I would suggest others to simply open a new issue so we can focus on their particular use case.

When opening an issue on this feedstock, please indicate how you installed *miniforge*. 

@Didou09, you seem to have used the anaconda installer, which is different than the `miniforge` installer.

**Comment by BrotherMarat** [comment]
@Didou09, i fixed it, found on some chines forum answer, you have error because of this line "ImportError: libffi.so.6: cannot open shared object file: No such file or directory"

i fixed that by running this command: ln -s libffi.7.dylib libffi.6.dylib

**Comment by GGDRriedel** [comment]
I still have this issue on Ubuntu, no solution yet. 

https://github.com/conda/conda/issues/11366 
This recommends updating conda, but that is just sending me into a loop of anaconda telling me that anaconda is up to date and should be updated

**Comment by hmaarrfk** [comment]
Soemtimes you got to "kick" it to the version you want.

```
conda install "conda>=24.7.1"
```

if the issue persists for you, please open a new one provided more installation info. Installation issues are quite tricky to troubleshoot without all the specifics.
