### ISSUE TITLE
Installer size now 200MB on linux (instead of 50MB) 

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#34]
Issue:

Since 4.8.3-3, the installer size is now 200MB.

See after on left, before on right (4.8.3-2
![image](https://user-images.githubusercontent.com/90008/82777671-a21b2580-9e03-11ea-8dca-b58470998a19.png)

**Comment by isuruf** [comment]
We should wait until we can find why the compilers are pulled in. See https://gitter.im/conda-forge/conda-forge.github.io?at=5ecacf9a27513a72fbad98c6

Do you mind if we marked the last release as  a pre-release?

**Comment by hmaarrfk** [comment]
Prerelease is fine

**Comment by isuruf** [comment]
Fixed with https://github.com/conda-forge/binutils-feedstock/pull/28
