### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by longglecc** [conda-forge/miniforge#345]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

OS： raspberry Pi OS （64-bit）
packages: Miniforge3-Linux-aarch64.sh

I created py3 environment cannot use pip, but the base environment can use pip normally，I couldn't find the cause of the problem, so I asked for help..

as image:
![image](https://user-images.githubusercontent.com/33145006/188597111-1cd9c069-f7e7-4957-a837-fb4431d185d4.png)

### Installed packages

```shell
Miniforge3-Linux-aarch64.sh
```

### Environment info

```shell
raspberry Pi OS （64-bit）
```

**Comment by longglecc** [comment]
> Can you please recreate the env and try again? Is this even still an issue?

As long as it is my created  new environment, there is this problem.

**Comment by hmaarrfk** [comment]
Can you please provide us the outputs of the following commands. all from within the base environment
* `conda info`
* `conda list`
* `conda list --name py3`

**Comment by longglecc** [comment]
> Can you please provide us the outputs of the following commands. all from within the base environment
> 
> * `conda info`
> * `conda list`
> * `conda list --name py3`

![image](https://user-images.githubusercontent.com/33145006/207210514-6f6ba748-3395-455d-a0a4-8e538407efa0.png)
![image](https://user-images.githubusercontent.com/33145006/207210628-11402684-7f57-4df6-93d2-ef9aa979c805.png)
![image](https://user-images.githubusercontent.com/33145006/207211409-36408e8d-df78-4747-99da-c777ade65b6d.png)
![image](https://user-images.githubusercontent.com/33145006/207211531-0b71491b-4ce2-4cf2-b1fc-c132065486ad.png)

**Comment by isuruf** [comment]
You are not using conda-forge for the `py3` environment and is using `pkgs/main`. While conda-forge supports raspberry pi, `pkgs/main` does not

**Comment by longglecc** [comment]
> You are not using conda-forge for the `py3` environment and is using `pkgs/main`. While conda-forge supports raspberry pi, `pkgs/main` does not

thanks, This problem has been solved.

**Comment by hhhhpaaa** [comment]
> 您没有将 conda-forge 用于环境，而是使用 .虽然 conda-forge 支持树莓派，但不支持`py3``pkgs/main``pkgs/main`

Thank you very much, I finally solved this problem that has been bothering me for a long time.

**Comment by Forest-Lee** [comment]
> You are not using conda-forge for the `py3` environment and is using `pkgs/main`. While conda-forge supports raspberry pi, `pkgs/main` does not

Thanks a lot, same question and this worked for me
