### ISSUE TITLE
update to conda 22.9.0

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/miniforge#352]
### Comment:

The latest conda version is 22.9.0: https://docs.conda.io/projects/conda/en/latest/release-notes.html#id1

The latest version here is 4.14.0.

**Comment by hmaarrfk** [comment]
I guess mamba doesn't support it yet. TBH, I think you can just update it when the time comes.

conda somewhat moves too quickly. I would add a line:

```
conda update --all --yes
```
if you are interested in staying on the bleeding edge.
