### ISSUE TITLE
miniforge matrix with python versions

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/miniforge#354]
### Comment:

It would be great if it's documented somwhere a matrix of miniforge version with python version e.g.

miniforge | python
4.14.0-0   | 3.10
4.12.0-0   | 3.9

**Comment by nickfraser** [comment]
I just want to 2nd that this would be very useful. Especially in situations where `miniforge` is being used within a docker container, where (usually for convenience) project dependencies may be installed directly into the base environment.

**Comment by hmaarrfk** [comment]
You can:
1. Create a conda environment with any version of python you want.
2. Create your own miniforge-like installer.


I think us maintaining this matrix would be too much maintenance.

**Comment by nickfraser** [comment]
Thanks for the quick response, I'm aware of the options you specified above. My comment was just to say such a matrix would be useful for some, myself included.

> I think us maintaining this matrix would be too much maintenance.

A shame, but perfectly reasonable. Apologies, my comment was not meant to sound like a demand - I love `miniforge` and appreciate the effort that has gone into it. It's been life-saver / time-saver for me in many-a-project.

**Comment by hmaarrfk** [comment]
The build matrix issue is real. I also think the fork suggestion is a really good one. There are likely laot of other foundational packages that you can predownload helping your CI pipeline.

To be honest, at this present time, the release of a new version, that i believe would reave issues for some, is blocked by the large matrix we presently offer.
