### ISSUE TITLE
Miniforge3 build for the new architecture Loongarch(64 bit)

### ISSUE THREAD

**Issue by liuxiang88** [conda-forge/miniforge#363]
### Comment:

Hi dears,
How can I build Miniforge3 on the new architecture--Loongarch,which is different from x86_64、aarch64?
How is the "conda-forge/miniforge/releases/download/4.14.0-1/Miniforge3-Linux-aarch64.sh" generated?
What can I do to generate Miniforge3-Linux-loongarch64.sh on Loongarch？
Thank you for your reply. I am looking forward to it.

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/miniforge/issues/196#issuecomment-893413284

**Comment by liuxiang88** [comment]
Thank you very much!
