### ISSUE TITLE
Install failure on macOS 10.13

### ISSUE THREAD

**Issue by inducer** [conda-forge/miniforge#373]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Is the minimum version of macOS needed for use of miniforge/conda forge documented somewhere? I ask because I run CI jobs on a (yes, seriously long in the tooth) mac with macOS 10.13.6, and miniforge recently stopped installing properly, with a symbol lookup failure:
```
dyld: Symbol not found: __ZNSt3__14__fs10filesystem16filesystem_errorD1Ev
  Referenced from: /Users/gitlabcirunner/builds/bb2c705e/0/inducer/pyopencl/.miniforge3/conda.exe
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/gitlabcirunner/builds/bb2c705e/0/inducer/pyopencl/.miniforge3/conda.exe
```
(See https://gitlab.tiker.net/inducer/pyopencl/-/jobs/480435)

I tried to look around for references in the documentation and the miniforge README as for what versions of macOS are supported, but I came up empty. Maybe I just missed it though.

### Installed packages

```shell
(none, just trying to install miniforge)
```

### Environment info

```shell
(miniforge won't install, so I can't provide this.)
```

**Comment by isuruf** [comment]
Requirements are
- macos 10.9 for darwin-x86_64
- macos 11.0 for darwin-arm64
- glibc>=2.12 for linux-x86_64
- glibc>=2.17 for other linux

Miniforge and all its dependencies should have the above requirements. If not, it's a bug. (In this case, it's a bug in micromamba).
Some individual packages may have higher OS requirements, but they will not be installable in an older OS.

It would be good to mention this in the README here and in conda-forge.github.io website.

**Comment by isuruf** [comment]
Should be fixed with the latest release.

We should open a new issue to document the required system versions.

**Comment by jakirkham** [comment]
Agreed. Wonder if we should just put that on the webpage (given it applies to more than the installers)?
