### ISSUE TITLE
Mambaforge-PyPy windows installer is broken

### ISSUE THREAD

**Issue by iloos** [conda-forge/miniforge#385]
### Comment:

Hey I installed the mamba PyPy on my Win10 machine, but I don't understand how to access it.  I already had anaconda installed. When opening the anaconda prompt, 'mamba' is not recognized. 

When tryinig to open the activate.bat, I get these error messages:
![image](https://user-images.githubusercontent.com/41428282/202816083-ac5e5770-bc4d-4472-a5d3-3a4dc297655e.png)
![image](https://user-images.githubusercontent.com/41428282/202816102-6126736e-2294-4628-91ff-134af1ac3741.png)
![image](https://user-images.githubusercontent.com/41428282/202816119-94a8f0f0-b73f-4f8c-9916-c29906d8ad21.png)

I was comfortably using anaconda, but am looking to share my projects and did some further research. Miniforge seems perfect for many reasons. But do i need to uninstall my old version of python or something? I did not add to defaults in the installer, is that it maybe?

Thanks!!

**Comment by iloos** [comment]
I can get it to work, by just installing mamba in anaconda, as per the docs, but I was wondering how this would work on a new machine.

**Comment by otaithleigh** [comment]
Just want to note that I get the same errors above with a fresh Win10 mambaforge-pypy3 installation, but it's specific to the PyPy version -- the CPython version works fine. I can then create an environment with pypy that works fine, but something about the mambaforge-pypy3 installer is borked.

**Comment by hmaarrfk** [comment]
cc: @conda-forge/help-pypy

**Comment by mattip** [comment]
Once I copied `libexpat.dll` from Library\bin to the root directory I could run activate.bat

**Comment by mattip** [comment]
I opened an issue in the pypy feedstock

**Comment by andrew-ma** [comment]
Just FYI, I faced this issue today when I used this installer (Mambaforge-pypy3-Windows-x86_64.exe). SHA256 hash = 1C107C97A953549BE553A09E80B4B32A5132476253606F79282FCD4ACBBF36B0

**Comment by lamrongol** [comment]
> And it was solved when I copied these 3 files to %USERPROFILE%\mambaforge-pypy3
> 
> * %USERPROFILE%\mambaforge-pypy3\Library\bin\ffi-8.dll
> * %USERPROFILE%\mambaforge-pypy3\Library\bin\libbz2.dll
> * %USERPROFILE%\mambaforge-pypy3\Library\bin\libexpat.dll

I had same problem and this way solved it. Installer should contains these dlls in `\mambaforge-pypy3` folder.

**Comment by mattip** [comment]
> Installer should contains these dlls in \mambaforge-pypy3 folder.

There is some discussion of this vs. alternate solutions in conda-forge/pypy3.6-feedstock#101

**Comment by olsonperrensen** [comment]
> > And it was solved when I copied these 3 files to %USERPROFILE%\mambaforge-pypy3
> > 
> > * %USERPROFILE%\mambaforge-pypy3\Library\bin\ffi-8.dll
> > * %USERPROFILE%\mambaforge-pypy3\Library\bin\libbz2.dll
> > * %USERPROFILE%\mambaforge-pypy3\Library\bin\libexpat.dll
> 
> I had same problem and this way solved it. Installer should contains these dlls in `\mambaforge-pypy3` folder.

Makes sense for it to work out of the box. Isn't there a request to merge this?

**Comment by mattip** [comment]
Copying the files is not an alternative the conda-forge maintainers wish to use. There is an alternative [proposed solution](https://github.com/conda-forge/pypy3.6-feedstock/issues/101#issuecomment-1552935352). It needs a champion to turn that into a PR to the [feedstock](https://github.com/conda-forge/pypy3.6-feedstock). I am willing to mentor someone who wishes to undertake it.

**Comment by h-vetinari** [comment]
The newest miniforge [builds](https://github.com/conda-forge/miniforge/releases/tag/23.3.1-1) should have fixed this. Can someone give it a try?

**Comment by isuruf** [comment]
Fixed now with https://github.com/conda-forge/pypy3.6-feedstock/pull/107
