### ISSUE TITLE
Miniforge unified installer for Linux (Unix?)

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#39]
Issue:
During the discussion of #38 

It is clear that at least some subset of users are confused by all the different linux installers.

It isn't always clear to an end user what platform they are on. For example, many using RaspberryPis don't always graps that they are using a different computer architecture than their laptops.

conda-forge has done quite well making many useful packages installable on x86, aarch, and ppc.

I think it might help users to get a "unified" installer that works for linux on all 3 architectures.

It might be 3x the size, but I think it would go a ong way to helping the user experience.

The user case would be:

1. Download a 200MB installer for "Linux"
2. Let the installer unpack the appropriate architecture on your machine. This will install the same 60MB that would be installed with the architecture specific installer.
3. Delete the 200MB installer.

conda already makes architecture specific decisions (e.g. downloading the package for the appropriate architecture for you) so it seems natural to have the installer work by the same principle.

For reference, Apple did this with 32bit and 64bit installers. And they are workign on doing the same with their Arm transition.

**Comment by isuruf** [comment]
I don't think this is viable as we add more architectures. I haven't see any fat installer for linux other than simple bash scripts that downloads the correct binary.

**Comment by hmaarrfk** [comment]
I guess I would just like a single line installer.

```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-`arch`.sh -O Miniforge3.sh
bash Miniforge3.sh
```

works for linux

does 

```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-`uname`-`arch`.sh -O Miniforge3.sh
bash Miniforge3.sh
```
also work for OSX?

**Comment by isuruf** [comment]
```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh -O Miniforge3.sh
bash Miniforge3.sh
```
works for Linux

**Comment by isuruf** [comment]
`uname` is `Darwin` on OSX.

**Comment by jakirkham** [comment]
Also there is no `wget` (at least not preincluded) on macOS. So this would need to be `curl`.

**Comment by hmaarrfk** [comment]
Curl doesn't come preincluded on ubuntu

**Comment by isuruf** [comment]
A shell script can check for `curl` and `wget` and use whatever is available.

**Comment by hmaarrfk** [comment]
But how do you get that shell script?

**Comment by isuruf** [comment]
curl or wget or your browser.

**Comment by isuruf** [comment]
For example, homebrew's installation instruction for OSX and Linux is,
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

**Comment by westurner** [comment]
Could instructions and/or a shell script for installing on a *ARM64* (`uname -m`)  Raspberry Pi (and Pinebook Pro) be added to this or another repository?

**Comment by nerohmot** [comment]
# Specifications
Let's note down what the unified installer should do. (feel free to add)

1. Determine the `operating system` and `processor type` of the host so it is able to download the correct underlying installer.
2. Have at least the same option set as the individual installers, so it can pass-through the options to the underlying installer. (eg. to change prefix, run in batch mode ...)
3. Have extra options to specify:
    - The desired `Python implementation` (otherwise we can't reach the PyPy installers from the unified installer)
    - The `size` (for now there is only `Mini`, but this can open the door to other sizes -see-below-)
4. Download also the `sha256` digests **and** check the installer against it.
5. Plug the security hole when installing for [multiple users](https://docs.anaconda.com/anaconda/install/multi-user/).
6. ?

---
# Sizes
Until now we have the `mini` size (cfr. the prefix of all currently available installers), it is the `conda-forge` equivalent of `miniconda` if you want, but with the added support for `aarch64` and `PyPy`, and based **solely** on the `conda-forge` channel.

Some people need the smallest possible package (probably for CI purposes where size equals time and money), other need a 'good' base environment (read: with also [conda-build](https://github.com/conda/conda-build), [mamba](https://github.com/TheSnakePit/mamba) and probably [boa](https://github.com/TheSnakePit/boa) too) while yet others just want the 'fat pack' (the `conda-forge` equivalent of `anaconda` if you want).

We can satisfy every bodies needs by adding `size` to the `unified Unix installer. Sise could be:
  - **minimal** : `Miniconda` as it is now. (for purists and CI guys)
  - **nominal** : a good base environment to install as base (for multi-user installations)
  - **maximal** : an `anaconda` like installer (for per-user installations where one wants to get on with the acctual work)

The unified Unix installer could default the size based on who is installing:
  - **root** : defaults to the `nominal` size.
  - **non-root** : defaults to the `maximal` size.
  - **sudo-er** : defaults to `non-root` (thus `maximal`), but get's a warning that he can do the setup for all users on the box (if not in batch mode)
  
The CI guys know what they want and probably don't even want to go through the `unified Unix installer`, and even if they do, they know how to access the `minimal` installer, so in IMHO these are sensible defaults.
  
**<ins>An interesting question</ins>** is : Do we need to make the underlying `nominal` and `maximal` installers, or can the `unified Unix installer` use just the existing `minimal` installers, to install and in a `post processing` step 'jump into' the installation and issue the needed commands to transform the minimal environment into a `nominal` or `maximal` one ? 
If we manage this, it would be particularity interesting for the `maximal` package, as we could attach our wagon to the anaconda train  (read: parse whatever they have at the moment of installation, feed it to mamba to find a `conda-forge` solution and install that ... it would basically be maintenance free :stuck_out_tongue_winking_eye:)

This script [conda-forge-installer.sh.txt](https://github.com/conda-forge/miniforge/files/4944669/conda-forge-installer.sh.txt) (dowload and remove the `.txt`) is basically working in the above outlined direction but needs some more work ... feel free to comment/contribute!

**Comment by hmaarrfk** [comment]
> nominal : a good base environment to install as base (for multi-user installations)
> maximal : an anaconda like installer (for per-user installations where one wants to get on with the acctual work)

I really don't think I want to encourage this kind of workflow. We will always miss an edge case. I've helped enough people troubleshoot their system, where I feel like it is just better to teach them to keep track of their environments.

I think anconda has a way to share environments across organizations and users.


```
conda create --name -f environment.yml
```

should be sufficient, and hits both those cases.

**Comment by nerohmot** [comment]
Indeed, I had something similar in mind from within the `unified Unix installer` (so no 'hoop jumping required) :smile: 

For `minimal` `conda create` will not do because as @wolfv explained :
>It would probably be possible to fix issue #83, although I think it's cleaner to install mamba in root.
>Conda also does not work properly when not installed in the root environment.
>And installing mamba in another environment will pull in a copy of conda (as mamba depends on conda).

but `conda install --name base -f minimal.yml` will do the trick.

For `maximal` that would become `conda install -n base -f maximal.yml`

I know, that a big installation in `base` is not encouraged (don't know who/why this is oracled), but this is the way `anaconda` is installed ... alternatively we could do a `conda install -n maximal -f maximal.yml` ... 

The `minimal.yml` is straight forward, but the `maximal` is not ... still meditating how this could be done ...

**Comment by abebeos** [comment]
@hmaarrfk , why so much talks, and not simply start with something basic (similar to what's included in numba) ?

```sh
#!/bin/bash

set -v -e

# Install Miniforge
unamestr=`uname`
arch='uname -m'


if [[ "$unamestr" == 'Linux' ]]; then
    wget https://github.com/conda-forge/miniforge/releases/download/4.9.2-7/Miniforge3-Linux-$arch.sh -O miniforge.sh
elif [[ "$unamestr" == 'Darwin' ]]; then
    wget wget https://github.com/conda-forge/miniforge/releases/download/4.9.2-7/Miniforge3-MacOSX-$arch.sh -O miniforge.sh
else
  echo Error
fi
chmod +x miniforge.sh
./miniforge.sh -b $1 $2 $3

```

**Comment by hmaarrfk** [comment]
I'm not too big of a fan of these kinds of scripts.

They either get people in the habbit of arbitrary code execution `run curl | sh` or assume a certain level of comfort with bash.

jakirkham also gave the good point of:

> Also there is no wget (at least not preincluded) on macOS. So this would need to be curl.

There is also alot of value of people understanding that arm != x86_64 when they have problems with their software.
conda-forge isn't at the stage yet where everything that works on x86_64 works on arm. Therefore, adding a bit of friction at the beginning might be beneficial in the long run.

**Comment by westurner** [comment]
If you're familiar with automated provisioning and/or continuous integration, scripting these kinds of things is necessary. Manually executing install instructions from a README is suboptimal compared to *one command in order to install the installer*.

FWIU, there's no GPG .asc to check for the miniforge release artifact (or for conda packages). 

There is a `check_sha256` function in the linked PR which checks the SHA256 checksums (that are retrieved over HTTPS, the same channel as the package and the install script) with `sha256sum`.


The linked PR downloads with wget or curl as appropriate. 
https://github.com/conda-forge/miniforge/pull/41/files#diff-1efda0b23f10c6d3235fb8ea157fc3957b1d669185a9803e27f83d4882aeff11R84-R97

There is no reason to inconvenience ARM users. The same install script with the same parameters should work just as well on ARM64 as on x86-64. Whether there are yet ARM64 builds for other packages is not relevant to miniforge's support for ARM64.

**Comment by hmaarrfk** [comment]
Thanks for bringing that PR back to light.

I think the main objection to that PR was the inclusion of the line:

```
         conda install -y mamba -n root -c conda-forge
```

which was controversial at the time. My main objection there was not to have a "special case" that we didn't want to support, be supported as part of our "supported installer".

Today, it seems better if the switch uses `Mambaforge` instead of `Miniforge` as opposed to manually installing mamba through a call to `conda`. An other solution might be not to have a switch at all, and to simply create two scripts.

My original goal when opening this issue was to have an unified **offline** installer. but having a unified **online** seems like a good starting point.

I will help review the PR if you open it. Otherwise, maybe I can find time this weekend.

**Comment by abebeos** [comment]
> I'm not too big of a fan of these kinds of scripts.

This is not about "being a fan", but about making CI work.

[...]
> There is also alot of value of people understanding that arm != x86_64 when they have problems with their software.
> conda-forge isn't at the stage yet where everything that works on x86_64 works on arm. Therefore, adding a bit of friction at the beginning might be beneficial in the long run.

Professionals ensure that other professionals do not need to waste their time with a toolset.

So, professionals strive for zero-friction,

Be professional.

**Comment by abebeos** [comment]
@isuruf , please! Those are far too basic things, not even worth disagreeing/discussing.

**Comment by ocefpaf** [comment]
@abebeos 'Be professional' is not ok and I ask you to understand that every conda-forge contributor is an unpaid volunteer. Please don't address @hmaarrfk in that manner again.

I understand that not getting what you need can be frustrating but the Miniforge team is doing an Herculean job helping many different people with diverse needs. Sometimes a particular one won't make the cut. Or more discussion may be needed.

Note that, if you require a coustom cut miniconda distro, you can contact AnacondaInc and hire their services. Then paid professionals will guarantee you will get what you require.

**Comment by hmaarrfk** [comment]
Honestly, looking back at this issue, it seems that isuruf and I had iterated quite a few times on a simple command that people can use in their CIs for various architectures

```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh -O Miniforge3.sh
bash Miniforge3.sh
```

https://github.com/conda-forge/miniforge/issues/39#issuecomment-652692122

This hits the Linux family. I think this largely alleviates the need to have dedicate script we must maintain, and test, and finally, write educational material for.

The big advantage here is that it uses known tools, without hiding details in yet an other script.

In my mind, this reduces friction quite a bit.

The advantage of having a script is that it solves the Mac/Linux compatibility. But then again, you need to use 
* curl to get the script on OSX
* wget to get the script on Linux

Maybe this isn't the case. I'm not too familiar with OSX details. I don't have an OSX computer, and as such, hitting that edge case isn't something I think I can contribute to very well.

Finally, in my experience, reducing the friction in downloading Miniforge3 on Linux/OSX is the least of an integrator's worries.

Personally, I'm more worried about people not updating their systems.....

**Comment by hmaarrfk** [comment]
you can try:

```
$(if hash curl; then echo -n curl --silent -o; else echo -n wget --quiet -O; fi) Miniforge3.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(if [[ $(uname) == "Darwin" ]]; then echo -n MacOSX; else echo -n $(uname); fi)-$(uname -m).sh
bash Miniforge3.sh
```

I also think you can be more creative if you need to add more configurations for a unified installer command.

I'm not sure this is any easier to read, or easier to teach a junior developer what is going on.

Scripts downloading scripts, and one line commands that has multiple if statements in them are VERY confusing for new developers who are often adept at only one subset of one programming language.

**Comment by westurner** [comment]
Just `curl`-ing or `wget`-ing does not check the checksum.

When you download a file to install on a computer, you SHOULD check the
checksum (and cryptographic signature) first.

Is there a CRC in the .tar.gz file format?

**Comment by westurner** [comment]
Is there an existing method for installing conda/mamba e.g. as root such
that the process-executing user cannot overwrite the source code? It's
called a W^X violation when code has write access to itself.

A default install of conda or mamba is editable by the user.

To say that "if you need to do permissions correctly, that's not supported"
is terribly counterproductive.

**Comment by isuruf** [comment]
> Just `curl`-ing or `wget`-ing does not check the checksum.

I don't see how we can fix it. If we have a script that does the checksum, how do we ensure that the script itself was correct?

**Comment by westurner** [comment]
This can be solved by distributing a public key over an already-keyed channel. The release artifact must be signed with a private key that corresponds to a verifiable public key.

The TUF: The Update Framework spec describes why and how not to trust the network or the package server file storage. 

> The Update Framework (TUF) helps developers maintain the security of software update systems, providing protection even against attackers that compromise the repository or signing keys. TUF provides a flexible framework and specification that developers can adopt into any software update system.

https://theupdateframework.io/

- https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#the-update-framework-specification

Is it all pointless because the conda packages aren't signed and the source packages' signatures aren't checked and the git commits aren't signed?
No, because ZIP, at least, does a CRC.

**Comment by hmaarrfk** [comment]
@westurner it seems that you and @nerohmot might have some ideas on what is missing in terms of security best practices. 

Please open a new issue focusing specificaly on security best practices and how we are breaking them.
If you know how we might implement these, a suggestion on how to do it would be useful.

You are correct that we are trusting the package server file storage. This is an assumption that I am presently making.

The original goal of this issue was to get to a easier way to install miniconda accross different architectures.

In my mind, a solution that compromises ease of use, download size, maintainability, understandability has been found in messages in July 2020. I'm sorry we never included it in the README.

**Comment by abebeos** [comment]
> @abebeos 'Be professional' is not ok and I ask you to understand that every conda-forge contributor is an unpaid volunteer.

It is very ok, and it the "voluteer" status is completely irrelevant.

> Please don't address @hmaarrfk in that manner again.

Fascinating use of "please" in context of dictating "expressional style" and "use of logic".

I've seen enough.

I just hoped to identify that the terrible quality of "miniconda" has at least a more professional community distro (miniforge).

It has not.

Leaving you "volunteers" talking things to death.

cu around.

**Comment by hmaarrfk** [comment]
Thanks everybody for you input.

As for the security discussion. Lets open a new issue to have a focused conversions.

The instructions:
https://github.com/conda-forge/miniforge/pull/122#event-4371358574

should help people setting up CIs learn our recommended to install Miniforge (and variants) in their own pipelines.

**Comment by abebeos** [comment]
@hmaarrfk , one last thing (and ensure you keep the rule in your brain once you extract it)

re #122, you "provide documentation to teach users how to solve a problem".

=> Teachers (and amateurish tool-developers) provide documentation to teach users to solve problems

=> Professional Tool-Developers provide a solution (here: script)

You are not in the role of a teacher here, so, switch to the role of a (professional) tool-developer, and provide the relevant abstractions/automations, instead of the documentation/instructions. See, nearly any professional reading your instructions will ask "Great, they could have provided a script instead of writing all this").

(the "sensitive souls" back off, this is from one intelligent being to another. See, I try to teach, a rule)

**Comment by ocefpaf** [comment]
I'm blocking this to avoid extra escalation. The tone in the abebeos are not OK and may even be a CoC violation.
