### ISSUE TITLE
The official version of python 3.11 has been released. When will it be supported?

### ISSUE THREAD

**Issue by kingmo888** [conda-forge/miniforge#391]
### Comment:

At least envs can support python 3.11,
If only there was a timetable.

**Comment by hmaarrfk** [comment]
See conda-forge.org/status/ specifically the migration.

You should already be able to build many environments

**Comment by hmaarrfk** [comment]
Probably for a while. I don't really have a timeline on that, nor do I really think it matters for the recommended workflow.

If you need specific environment, I think you should just create your own environment, with specified versions.

We use the freely available CIs from github to build this. You are free to fork this project, adjust it, and create your own installer.
