### ISSUE TITLE
Python 3.11.1 fixes the memory leak in 3.11.0. 

### ISSUE THREAD

**Issue by kingmo888** [conda-forge/miniforge#397]
### Comment:

When will it be supported?

**Comment by hmaarrfk** [comment]
Miniforge is pinned on python 3.10 for now.

Please open an issue on the python feedstock.

**Comment by hmaarrfk** [comment]
There is an open PR for 3.11.1 in the mentionnned feedstock. It seems patches need updating. Feel free to help on that front.

Once it is merged, it will be possible.
