### ISSUE TITLE
Error in installer on Ubuntu 18.04

### ISSUE THREAD

**Issue by AGSaidi** [conda-forge/miniforge#40]
Issue: Error in installer o Ubuntu 18.04
```
./Miniforge3-4.8.3-4-Linux-aarch64.sh: 404: ./Miniforge3-4.8.3-4-Linux-aarch64.sh: [[: not found
```
The line in question `        if [[ $SHELL = *zsh ]]` appears to be a bash-ism that Ubuntu's dash doesn't like.

**Comment by scopatz** [comment]
This is probably an issue in conda constructor

**Comment by AGSaidi** [comment]
Created https://github.com/conda/constructor/issues/348 and going to close this as that appears to be where the offending line comes from. Thanks!

**Comment by hmaarrfk** [comment]
Lets keep this issue open.

We should close this issue when we rebuild a new version of miniforge that works with ubuntu natively.
