### ISSUE TITLE
Cannot create environment with specified version of python

### ISSUE THREAD

**Issue by taise-hikawa** [conda-forge/miniforge#403]
### Comment:

I wanted to create environment with specified version of python, but I couldn't.
```
$ conda create -n py39 python=3.9
$ conda activate py39
$ conda info
```
```
python version : 3.8.6.final.0
```
Are there any other operations required?

### environment
- pc device: Mac Studio（2022）Apple M1 Max
- os version: Monterey 12.5
- miniforge version: conda 22.11.1

### update (2023/01/13 06:08(GMT))
I installed it thinking I should use arm64 support, but it didn't solve the problem.
```
$ wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh
```

**Comment by isuruf** [comment]
`conda info` gives you the python version of the base environment. run `python --version`.

**Comment by taise-hikawa** [comment]
Thank you very much. Problem solved.
