### ISSUE TITLE
Documentation on the trade-offs of mambaforge vs mambaforge-pypy 

### ISSUE THREAD

**Issue by arturdaraujo** [conda-forge/miniforge#404]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Wondering which one I should pick.

It seems that "ideally" we should pick mambaforge-pypy. 

I've used conda with libmamba solver for a while now but I'm considering to change to mamba-forge (I've tested on my other PC recently and it works great! I'm using the latest release 1.1.0). 

So to clarify my question: 
I think mamba forge is mini forge with libmamba solver, right? But what about pypy? Is it a even faster mamba-forge? If pypy is faster then why not drop the mamba-forge entirely and just use mamba-forge pypy? If there is more to it would be nice some clarification on the documents for people like me who are not familiar with these packages, people who just want to download this thing to "mamba create -n env" and "mamba install foo" that. 

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by hmaarrfk** [comment]
We have not pre-installed libmamba solver anywhere yet. We were experimenting with it a while back, just never materialized.

https://github.com/conda-forge/miniforge/blob/main/Miniforge3/construct.yaml#L30

Mambaforge = miniforge3 + mamba pre-installed.

You should use pypy if you want.

**Comment by hmaarrfk** [comment]
We already say this in the Readme
![image](https://user-images.githubusercontent.com/90008/212431237-dbfba2ee-c04a-46bb-8786-8f079cc2ee0e.png)


is there any other info you would like to add?

**Comment by arturdaraujo** [comment]
Yes! I was wondering what about pypy? what does it do? Is there any limitations to it if I install mamba forge with pypy? 
I'm more intrigued about mambaforge vs mambaforge-pypy

**Comment by hmaarrfk** [comment]
The installer just affects what you have installed in the `base` environment. You can install whatever you want in other environments.

I would suggest you leave your current base environment as is, and experiment with pypy in your standard workflow.

If you want the `conda` command to be powered by pypy, then you should install pypy in the base environment, but that is pretty niche.
