### ISSUE TITLE
Any difference between miniforge and anaconda that can cause the following problem?

### ISSUE THREAD

**Issue by michalisk13** [conda-forge/miniforge#408]
### Comment:

Hi,

I am trying to run a project and I am issuing the following commands:

conda env create -f environment.yml
source activate securityssidabi38

and I get

```
EnvironmentNameNotFound: Could not find conda environment: securityssidabi38
You can list all discoverable environments with `conda info --envs`.
```

```
# conda environments:
#
base                  *  /home/user/mambaforge
```

Any idea what may be causing the problem?

Thanks,
Mak

**Comment by jakirkham** [comment]
Would need the contents of `environment.yml` to know

**Comment by michalisk13** [comment]
Hi,

Thanks for the reply.

Here is the link for the file

https://github.com/GISDev01/security-ssid-abi/blob/main/environment.yml

**Comment by jakirkham** [comment]
What was the resolution?

**Comment by michalisk13** [comment]
I've just installed the dependencies manually. I don't see the usefulness of all those tools nowadays... Especially for certain small scale projects

**Comment by hmaarrfk** [comment]
Typically pinning so hard creates conflicts. You might have to relax the strict channel priority for example.
