### ISSUE TITLE
New 22.11.1-0  .sh installers broken in interactive mode

### ISSUE THREAD

**Issue by dbast** [conda-forge/miniforge#413]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

see https://github.com/conda/constructor/issues/635

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by hmaarrfk** [comment]
operating system? all?

**Comment by hmaarrfk** [comment]
On linux 64, it gets to:
```
Transaction finished
installation finished.
Do you wish the installer to initialize Mambaforge
by running conda init? [yes|no]
Mambaforge.sh: line 410: DEFAULT: unbound variable
```

**Comment by hmaarrfk** [comment]
I pulled it from the latest release.

**Comment by hmaarrfk** [comment]
The issue is that `DEFAULT` is never defined. The logic that sets it can be `yes`, `no` or never defined.

**Comment by hmaarrfk** [comment]
xref: https://github.com/conda/constructor/blob/main/constructor/header.sh#L534

**Comment by dbast** [comment]
@hmaarrfk Thanks for figuring that all out... It was very late yesterday here, but I still wanted to report it without the time to write all details... though some details have bin in the referenced constructor issue. This PRs should have fully fixed/worked around that now.
