### ISSUE TITLE
22.11.1-2 creates a micromamba folder in my home directory

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#420]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Latest release [22.11.1-2](https://github.com/conda-forge/miniforge/releases/tag/22.11.1-2) seems to create `${HOME}/micromamba` or `$(pwd)/micromamba` at installation time.

cc @conda-forge/constructor 

### Installed packages

```shell
.
```

### Environment info

```shell
     active environment : base
    active env location : /home/mark/mambaforge
            shell level : 1
       user config file : /home/mark/.condarc
 populated config files : /home/mark/mambaforge/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/mark/mambaforge  (writable)
      conda av data dir : /home/mark/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/mark/mambaforge/pkgs
                          /home/mark/.conda/pkgs
       envs directories : /home/mark/mambaforge/envs
                          /home/mark/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.8 Linux/5.15.0-58-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
I'm somewhat surprised that this issue didn't occur earlier since the last time we updated micromamba was a few months back https://github.com/conda-forge/miniforge/pull/383

It is due to a bug in micromamba: https://github.com/mamba-org/mamba/issues/2187

I think we could accelerate the release of https://github.com/mamba-org/mamba/pull/2265

but the same people that would review a patch proposed for the conda-forge only version would review a patch for the upstream repository.

I can apply the patch to conda-forge once they accept it there.

**Comment by hmaarrfk** [comment]
I am somewhat eager to get this one line change into micromamba. These two bugs are somewhat big enough for me to want to pull the latest release :/

**Comment by timostrunk** [comment]
Can the micromamba folder be safely deleted after the install is done or will this break the mamba installation, which was carried out?

**Comment by hmaarrfk** [comment]
Yes. Safe to delete
