### ISSUE TITLE
Scoop failed to install mambaforge

### ISSUE THREAD

**Issue by YWtheGod** [conda-forge/miniforge#427]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

scoop run the mambaforge installer with /S silent mode, and I found that the installer just quit immediately and let the installing job run in background. so when the scoop script got the control again, no files were actually installed, so the script failed to find the file pythonw.exe, and raise an exception and the installtion got interrupted.

### Installed packages

```shell
install failed
```

### Environment info

```shell
install failed
```

**Comment by YWtheGod** [comment]
scoop can install mambaforge version 22.9.0-2 without problem, but not on lastest release.

**Comment by jaimergp** [comment]
See #421
