### ISSUE TITLE
How to install a specified version of python using mambaforge?

### ISSUE THREAD

**Issue by Legend94rz** [conda-forge/miniforge#431]
### Comment:

By default, if I download and install using the script:
`https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh`,
it will install python 3.10. It's too new for my project and there're some  compatibility issues when using py3.10.

Is there any way to install python 3.9 via mambaforge install sh instead of create another virtual environment?
Something like anaconda, I can use another "legacy" version of anaconda install script.

Thanks.

**Comment by hmaarrfk** [comment]
https://conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-python

**Comment by hmaarrfk** [comment]
Most people suggest that "best practices" mean to not use the "base" environment and to create virtual environments for your different projects.

If you insist on using the base environment, you may use Mambaforge/Miniforge 4.13. Looking at our history that seems to be when we switched over. https://github.com/conda-forge/miniforge/pull/333/files#diff-faa2e4718e45104bcbb7bbd2a41537c729a7e1d2994128d3527379d13b1978c4R1


Again, you can always create your own miniforge-like installer to customize it however you want to.
