### ISSUE TITLE
mamba not found after fresh install from mambaforge on Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by rbavery** [conda-forge/miniforge#433]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

on a fresh install of mambaforge, the path is not set by the installer and mamba is not found. my home path is `/home/ubuntu` on an EC2 instance 

```
 wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
bash Mambaforge-Linux-x86_64.sh -b

```

```output
Linking conda-22.11.1-py310hff52083_1
Linking mamba-1.1.0-py310h51d5547_3
Transaction finished
installation finished.
```
```
mamba
```
```output
mamba not found
```

I would expect mamba to be available after running the bash script. exiting and then re-sshing or rebooting did not make mamba available.

### Installed packages

```shell
not applicable
```

### Environment info

```shell
not applicable
```

**Comment by hmaarrfk** [comment]
batch modes doesn't "install" the conda hooks. You have to initialize the conda and make `conda` work manually if you use batch mode.

**Comment by rbavery** [comment]
got it thank you! I'm not sure exactly where but I think I saw the -b flag online somewhere

**Comment by fantasy-fish** [comment]
> batch modes doesn't "install" the conda hooks. You have to initialize the conda and make `conda` work manually if you use batch mode.

Hi I met the same problem even if I don't use `-b`

**Comment by hmaarrfk** [comment]
please use sudo with caution.

I would suggest you do not use sudo until you absolutely need to.

It likely installed to `/root/mambaforge` and not to your user's directory.

Please try again without `sudo`.

If you have other troubles, please open a new issue with your specific usecase.
