### ISSUE TITLE
Remove Anaconda channels from Mambaforge by default

### ISSUE THREAD

**Issue by jonashaag** [conda-forge/miniforge#447]
On the Mamba bug tracker we regularly have people report issues that are caused by mixing conda-forge and the Anaconda channels, which can be incompatible eg. if you use packages that use shared libraries.

As part of the Mamba issue template we already require people to acknowledge this fact but it still seems common for people to mix the channels. 

Is there a way to remove the Anaconda channels with the default installation of Mambaforge? If so I propose to do so.

**Comment by isuruf** [comment]
conda-forge is the only channel when mambaforge is installed. Usually people will use an environment file with defaults added as a channel. Nothing we can do about it.

**Comment by jonashaag** [comment]
😕
