### ISSUE TITLE
Dependency solver failure installing uvicorn with Mambaforge-pypy3

### ISSUE THREAD

**Issue by jfennick** [conda-forge/miniforge#456]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm getting the following error installing uvicorn into a brand new environment (and in a Docker container) when using Mambaforge-pypy3, but not using miniconda. Here is my minimal reproducible Dockerfile:

```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget

RUN CONDA="Mambaforge-pypy3-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge-pypy3 && \
    rm -f $CONDA
ENV PATH /mambaforge-pypy3/bin:$PATH

RUN conda install uvicorn
```

This fails with:
```
#7 150.6 UnsatisfiableError: The following specifications were found to be incompatible with each other:
#7 150.6
#7 150.6 Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
#7 150.6
#7 150.6   - feature:/linux-64::__unix==0=0
#7 150.6   - feature:|@/linux-64::__unix==0=0
#7 150.6   - uvicorn -> click[version='>=7.0'] -> __unix
#7 150.6   - uvicorn -> click[version='>=7.0'] -> __win
#7 150.6
#7 150.6 Your installed version is: 0
```

However, the following Dockerfile works, so the problem does not appear to be with the uvicorn package.
```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget

RUN MINICONDA="Miniconda3-latest-Linux-x86_64.sh" && \
    wget --quiet https://repo.continuum.io/miniconda/$MINICONDA && \
    bash $MINICONDA -b -p /miniconda && \
    rm -f $MINICONDA
ENV PATH /miniconda/bin:$PATH

RUN conda install uvicorn
```

### Installed packages

```shell
none
```

### Environment info

```shell
N/A
```

**Comment by jfennick** [comment]
I just found this open issue: https://github.com/conda-forge/click-feedstock/issues/45

**Comment by jaimergp** [comment]
Most probably not due to the installer itself, but to the constraints imposed by the packages present in their different `base` environments.

Can you add a `RUN conda list -n base` to both Dockerfiles? With those we can run dry-run solves and see what's going on with different solver backends.

**Comment by jfennick** [comment]
```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget

# NOTE: Use regular Mambaforge, NOT Mambaforge-pypy3 because uvicorn is incompatible with pypy.
# See https://github.com/encode/uvicorn/blob/28fc4bdb77d1bd2f541ca7e0b3bd6fe1155e162f/pyproject.toml#L42
# (This is NOT the same thing as using Mambaforge-pypy3 and simply not installing pypy!)

RUN CONDA="Mambaforge-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge && \
    rm -f $CONDA
ENV PATH /mambaforge/bin:$PATH

RUN conda install uvicorn
```

This Dockerfile works. Apparently `platform_python_implementation != 'PyPy'` is False for Mambaforge-pypy3, even if pypy is not explicitly installed. This was not obvious to me, and perhaps could be improved in the documentation.

**Comment by hmaarrfk** [comment]
When you install `Mambaforge-pypy3` `pypy` is installed in the base environment.

**Comment by jfennick** [comment]
Yes, in the base environment _only_. If you create another environment, you can indeed install uvicorn with Mambaforge-pypy3
```FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget

RUN CONDA="Mambaforge-pypy3-Linux-x86_64.sh" && \
    wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/$CONDA && \
    chmod +x $CONDA && \
    ./$CONDA -b -p /mambaforge-pypy3 && \
    rm -f $CONDA
ENV PATH /mambaforge-pypy3/bin:$PATH

RUN mamba create --name nopypy
RUN mamba install --name nopypy uvicorn
```

Note that the pypy executable (`which pypy`) is available in both base and nopypy, but the pypy python package is only in base. Hence, the dependency conflict only occurs in base. This was the source of my confusion.
