### ISSUE TITLE
A mambaforge edition with Spyder preinstalled (for teaching)

### ISSUE THREAD

**Issue by BjornFJohansson** [conda-forge/miniforge#461]
### Comment:

Hi all, I think that a mambaforge installer with spyder included would be great for teaching.

I have biology students that I try to teach introductory Python and I have previously used the Anaconda Personal Edition.
This has the advantage of installing Spyder so that it is reachable from the Windows menu. I find it especially valuable do have the students %pip install what is needed from the Spyder console. This way I can bypass the console altoghether.

However, this is a huge and slow install, so I wonder if it would be hard to make a derivative with Spyder and its dependencies?

**Comment by isuruf** [comment]
@BjornFJohansson, this should be easy to set it up in your personal fork of miniforge.
- Fork miniforge
- Enable Github CI
- Add `spyder` to https://github.com/conda-forge/miniforge/blob/main/Miniforge3/construct.yaml
- Tag a release with conda version number and build number. E.g. `23.1.0-2`

**Comment by BjornFJohansson** [comment]
Closing
