### ISSUE TITLE
Update conda version to 4.8.4

### ISSUE THREAD

**Issue by hajapy** [conda-forge/miniforge#47]
Issue:
Conda 4.8.4 has been released, including some bug fixes. Should we package miniforge with this version?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hmaarrfk** [comment]
I believe isuruf is half way through the release process.

https://github.com/conda-forge/miniforge/releases

**Comment by hmaarrfk** [comment]
It seems to be failing in some weird situation
https://travis-ci.com/github/conda-forge/miniforge/jobs/371809305#L666

**Comment by hmaarrfk** [comment]
I think this was finally released.
