### ISSUE TITLE
Miniforge-pypy3 should contains pypy 3.10

### ISSUE THREAD

**Issue by lamrongol** [conda-forge/miniforge#471]
### Comment:

From PyPy v7.3.12, it includes python 3.10.
https://www.pypy.org/posts/2023/06/pypy-v7312-release.html

It is needed in the disscussion https://github.com/conda-forge/pypy3.6-feedstock/issues/104

Especially, when using `scikit-learn`, normal pypy doesn't work and only miniforge-pypy can work.

**Comment by hmaarrfk** [comment]
We can't use things we didn't package. We need pypy3.10 first.

Let's let the discussion you pointed to play out.

Please provide constructive input there.
