### ISSUE TITLE
Still the best for Apple Silicon ?

### ISSUE THREAD

**Issue by underthesand** [conda-forge/miniforge#486]
### Comment:

i heard miniconda is now better for M1/M2 chips. I thought miniforge was always ahead of miniconda, is that still the case?

**Comment by jaimergp** [comment]
Miniconda has osx-arm64 [installers](https://docs.conda.io/projects/miniconda/en/latest/), yes, if that's what you are asking. I don't know what "better" or "ahead of" would mean here, but you can get a working `conda` installation without Roseetta using either.

The only difference is which channel packages are coming from and default in the configuration (`conda-forge` for Miniforge, `defaults` for Miniconda). Ah, and the presence of the `mamba` CLI tool (Miniconda "only" has conda + conda-libmmaba-solver).

**Comment by underthesand** [comment]
Conda-forge has a lot of packages, and mamba is fast, so I'm going to continue using Miniforge. However, the general recommendation seems to be shifting towards using Miniconda now that it has osx-arm64 support.

**Comment by hmaarrfk** [comment]
seems like the conversation is resolved.
