### ISSUE TITLE
documentation "bug"

### ISSUE THREAD

**Issue by knabbers** [conda-forge/miniforge#498]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

"Latest installers with Python 3.10 (*) in the base environment:"

I read this as "you need python 3.10 to install this", so installed python 3.10 on my system.
But it means that _the installer_ will install python3.10 for you in mamba's base env.
Surely a few other simpletons will read it as the same, and it's an easy clarification to make.

### Installed packages

```shell
na
```

### Environment info

```shell
na
```

**Comment by hmaarrfk** [comment]
I'm happy to consider alternate wording. Now that you have had a bit of experience with conda, please feel free to make a suggestion
