### ISSUE TITLE
Mambaforge is installed - What are the consequences for me?

### ISSUE THREAD

**Issue by herry23xet** [conda-forge/miniforge#502]
### Comment:

I have `Mambaforge` installed on my macOS. So before September 2023.

I do not quite understand what consequences this has now for me as a user of `Mambaforge`.

What do I have to do now? (Especially if `Mambaforge` is discarded, but also because there is no support anymore).

Should I uninstall `Mambaforge` and install `Miniforge` afterwards?
And does `Miniforge` then also include `Mamba`?

Unfortunately, this is not quite clear from this page.

Above all, `Mambaforge` is also still recommended in `Mamba`'s documentation:
https://mamba.readthedocs.io/en/latest/mamba-installation.html

**Comment by hmaarrfk** [comment]
These are meerly installers. once "miniforge" or "mambaforge" is installed, it is similar to having a conda environment, at this point, you can use conda or mamba, whichever you like to keep it up to date.

**Comment by herry23xet** [comment]
Thx!
