### ISSUE TITLE
which one do i install Mambaforge-Windows-x86_64.exe or Mambaforge-pypy3-Windows-x86_64.exe or Mambaforge-pypy3-23.3.1-1-Windows-x86_64.exe or Mambaforge-23.3.1-1-Windows-x86_64.exe

### ISSUE THREAD

**Issue by stunlocked1** [conda-forge/miniforge#509]

**Comment by hmaarrfk** [comment]
Please have a look at our readme.

if you want a better response. please try to pose your questions in a more constructive way.

**Comment by stunlocked1** [comment]
> Please have a look at our readme.
> 
> if you want a better response. please try to pose your questions in a more constructive way.

ok whats the difference between Mambaforge-Windows-x86_64.exe and Mambaforge-23.3.1-1-Windows-x86_64.exe

**Comment by hmaarrfk** [comment]
the fact that the version is in the filename.

**Comment by stunlocked1** [comment]
> the fact that the version is in the filename.

then why it there another file without the version in the filename?

**Comment by hmaarrfk** [comment]
honestly, i just don't want to reply to this particular thread anymore.

Please open a new issue to ask your question taking into account the feedback you received from here in the way you organize it.

**Comment by stunlocked1** [comment]
> honestly, i just don't want to reply to this particular thread anymore.
> 
> Please open a new issue to ask your question taking into account the feedback you received from here in the way you organize it.

ok
