### ISSUE TITLE
whats the difference between Mambaforge-Windows-x86_64.exe and Mambaforge-23.3.1-1-Windows-x86_64.exe

### ISSUE THREAD

**Issue by stunlocked1** [conda-forge/miniforge#510]
### Comment:

the fact that the version is in the filename

then why it there another file without the version in the filename?

**Comment by hmaarrfk** [comment]
They are to help people that want to have the version in the file name.

If you work with conda for some time, you will have many of these installers lying around, it is useful to be able to refer to things by name.

It is useful to "freeze" versions in scripts sometimes. you can't do that easily if the name isn't in the url or in the executable.

In the future please try to give context to your questions:

1. Why is this a problem for you?
2. Would you think that this information is important for others.
3. Have you tried the installers? Have you seen a noticeable difference?

**Comment by stunlocked1** [comment]
> They are to help people that want to have the version in the file name.
> 
> If you work with conda for some time, you will have many of these installers lying around, it is useful to be able to refer to things by name.
> 
> It is useful to "freeze" versions in scripts sometimes. you can't do that easily if the name isn't in the url or in the executable.
> 
> In the future please try to give context to your questions:
> 
> 1. Why is this a problem for you?
> 2. Would you think that this information is important for others.
> 3. Have you tried the installers? Have you seen a noticeable difference?

so they are the same file just with a different filename?

**Comment by hmaarrfk** [comment]
yes https://github.com/conda-forge/miniforge/blob/main/scripts/build.sh#L86
