### ISSUE TITLE
Current miniforge installer for Debian Linux on Raspberry Pi 4 Model B fails on Unpacking payload step

### ISSUE THREAD

**Issue by MBraddock** [conda-forge/miniforge#527]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Summary
Attempting to install miniforge on Debian, when trying to run bash script, installer fails with note saying that there is no file or directory ~/miniforge3/conda.exe

### Steps to Reproduce
Attempted to run the following, both give same output:
First, the commands from this repo:
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh

Second, the commands from this link (rewriting for miniforge rather than miniconda) https://docs.conda.io/projects/miniconda/en/latest/:
mkdir -p ~/miniforge3
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh -O ~/miniforge3/miniforge.sh
bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3

Both of these get me to the following error:
PREFIX=/home/[My Username]/miniforge3
Unpacking payload ...
/home/[My Username]/miniforge3/miniforge.sh: line 355: /home/[My Username]/miniforge3/conda.exe: No such file or directory

dir miniforge3 now has the following files
conda.exe install_tmp miniforge.sh

I have also tried this with multiple versions of miniconda, anaconda but get the same behaviour with all.

I've looked in my directory to remove all old files that may be interfering, directories - didn't/dont have any .condarc or .conda files.

### Environment Information
OS - Raspbian GNU/Linux 11 (bullseye)
Kernel - Linux 6.1.21-v8+
Architecture - arm64
Raspberry Pi 4 Model B, Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz.

Any help/advice would really be much appreciated.

### Installed packages

```shell
N/A - Fails on install
```

### Environment info

```shell
N/A - Fails on install
```

**Comment by hmaarrfk** [comment]
did you make sure to download: `Raspberry Pi OS (64-bit)` and not `Raspberry Pi OS`?

**Comment by MBraddock** [comment]
Hi - have been looking at this today and do believe that this is my misstep - was seeing arm64 so thought I was on 64-bit architecture, but running getconf LONG_BIT returned 32.

Currently waiting for a microsd reader to arrive to reinstall my OS as the 64-bit version and will then re-try the install.

Still very inexperienced with Linux OS and RPi, so really appreciate the quick response!
