### ISSUE TITLE
Question: Has miniforge dropped python2 support? Would maintaining support for py2 and py3 be crazy?

### ISSUE THREAD

**Issue by zbeekman** [conda-forge/miniforge#54]
Sorry to ask in an issue, but after reading CONTRIBUTING.md it wasn't clear that there was a better alternative.

First off, yes, I know that Python2 reached EOL already, and I am not asking for Miniforge to support Python2. I am just looking for confirmation and clarification of my current impressions that:

1. Miniforge did indeed drop Python2 support, and
2. That this was done because other projects on which Miniforge depends have stopped supporting python2

The reason I ask is that I'm wrapping up a large Python3 porting task at work (better late than never) and we use [a fork of Miniforge](https://github.com/ParaToolsInc/CommanderConda) (that I maintain) to provide a smallish stand-alone python distribution and all of the dependencies of our software package. I had been attempting to maintain python2 compatibility but as the porting process of our main app progressed it became clear that this was going to cause challenges that would not be worth the flexibility of supporting Python2 and 3 in our main package. A few months back my Python2 conda distribution (based on Miniforge) started failing to build due to what appear to be package incompatibilities. These are most likely caused because the python community has started to drop support for Python2.

I just wanted to reach out and confirm that my initial impression that supporting a miniforge-like conda distribution that is python2 and python3 compatible would be challenging at best, if not impossible.

Thanks for the great project and any feedback you can provide!

**Comment by scopatz** [comment]
Hi there @zbeekman - as per [CFEP-15](https://github.com/conda-forge/cfep/blob/master/cfep-15.md) conda-forge as a whole has dropped Python 2

**Comment by jakirkham** [comment]
Would add I don't think Miniforge dropped Python 2 installers (or support thereof) as there weren't any to begin with. Miniforge installers have always used Python 3.

Also would note one can still create environments with Python 2 and packages needing it. This is the recommend usage with any Python version anyways (namely using new environments instead of installing in `base`). We just are not updating Python 2 packages in conda-forge any more as Anthony already said.

**Comment by scopatz** [comment]
Yeah, good point @jakirkham! We never made miniforge installers with Python 2 in the first place.  I think at this point it wouldn't make a ton of sense to take on that maintenance burden either.

**Comment by zbeekman** [comment]
Great, thanks so much @scopatz and @jakirkham!

Thanks to all of this info I'm going to go ahead and drop Python2 support in our custom distribution based on miniforge... There have been build issues since at least June (we have nightly testing) and it seems like it's going to be too much of a headache to try to maintain support for this. As I mentioned, the application which we're using our miniforge fork to support has (finally) been ported to python3 and during that process I was intending to maintain compatibility with 2 and 3 but there are a number of places where the complexity of doing this far outweighs the benefits. So if we're not supporting python2 in the application (https://github.com/ParaToolsInc/taucmdr) then there is no need for me to try to support python2 in [CommanderConda](https://github.com/ParaToolsInc/CommanderConda)

Thanks again for the speedy and thorough replies!
