### ISSUE TITLE
Making 23.11.0-0 the latest release

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#544]
### Comment:

I realize that I never made 23.11.0-0 the latest release.

If there are no objections by Sunday Jan 14 12-noon New York Time, I will make the the "latest" in the afternoon.

https://github.com/conda-forge/miniforge/releases/tag/23.11.0-0

**Comment by hmaarrfk** [comment]
cc: @mbargull @beckermr @jaimergp

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by beckermr** [comment]
Huzzah! Let it rip!

**Comment by BenjaminDbb** [comment]
please release the "latest" version

**Comment by hmaarrfk** [comment]
done.
