### ISSUE TITLE
Truststore dependency with Python 3.9

### ISSUE THREAD

**Issue by matteoriccioare** [conda-forge/miniforge#545]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi, I have been able to install all my packages with mamba on Python 3.9 without any error until yesterday.
I'm getting an error for truststore not being installable because Python version is <3.10. I'm aware the package is not supported but I don't really need to install it and can't understand why it used to work until yesterday (I build several times a week through Docker so always a clean environment).

**A simple "mamba install -y python=3.9" would raise the error.**

I've been trying to set ssl_verify to False in conda config prior to the various installations but this hasn't been doing the trick.

Is there anyway to avoid having the truststore dependency/not installing it? As I said again, I'm not using the package at all and I can't really upgrade to Python 3.10 right now.

Many thanks

### Installed packages

```shell
none
```

### Environment info

```shell
active environment : base
   active env location : /home/matteo.riccio/conda_folder
           shell level : 1
      user config file : /home/matteo.riccio/.condarc
populated config files : /home/matteo.riccio/conda_folder/.condarc
                         /home/matteo.riccio/.condarc
         conda version : 23.11.0
   conda-build version : not installed
        python version : 3.10.13.final.0
                solver : libmamba (default)
      virtual packages : __archspec=1=skylake
                         __conda=23.11.0=0
                         __cuda=12.0=0
                         __glibc=2.36=0
                         __linux=6.1.0=0
                         __unix=0=0
      base environment : /home/matteo.riccio/conda_folder  (writable)
     conda av data dir : /home/matteo.riccio/conda_folder/etc/conda
 conda av metadata url : None
          channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                         https://conda.anaconda.org/conda-forge/noarch
         package cache : /home/matteo.riccio/conda_folder/pkgs
                         /home/matteo.riccio/.conda/pkgs
      envs directories : /home/matteo.riccio/conda_folder/envs
                         /home/matteo.riccio/.conda/envs
              platform : linux-64
            user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Linux/6.1.0-7-amd64 debian/12.0 glibc/2.36 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
               UID:GID : 1025:1025
            netrc file : None
          offline mode : False
```

**Comment by xhochy** [comment]
Can you please post the actual error you get?

**Comment by matteoriccioare** [comment]
> Can you please post the actual error you get?

This is the error:

#7 20.84 Looking for: ['python=3.9', "conda-build"]
#7 20.84 
#7 20.84 Could not solve for environment specs
#7 20.84 The following packages are incompatible
#7 20.84 ├─ python 3.9**  is requested and can be installed;
#7 20.84 └─ truststore is not installable because it requires
#7 20.84    └─ python >=3.10  but there are no viable options
#7 20.84       ├─ python [3.10.0|3.10.1|...|3.12.1] conflicts with any installable versions previously reported;
#7 20.84       └─ python 3.12.0rc3 would require
#7 20.84          └─ _python_rc, which does not exist (perhaps a missing channel).

**Comment by xhochy** [comment]
Can you also list a `conda list` of the environment you run this command in?

**Comment by hmaarrfk** [comment]
> but I need to use the base environment...

You can install an older version of our installer. You may pin to a pretty old version of our installer 4.13.0-0
https://github.com/conda-forge/miniforge/pull/333/files


But you can always build your own Miniforge installer

**Comment by hmaarrfk** [comment]
I'm closing because we cannot unfortunately support such a large matrix of python versions for this installer. A conda-environment can likely fill your needs. Using the base is often not a requirement, more of a "convenience". Even the "base" environment is a "conda environment".
