### ISSUE TITLE
Can Windows arm64 be supported?

### ISSUE THREAD

**Issue by AlexanderDash** [conda-forge/miniforge#547]
### Comment:

Compiling with x64 will lag for a while, it's too uncomfortable.
I want to know if the installation package for miniforge in Windows arm64 can be easily created? If Windows arm64 is not easy to come up with, forget it, let's see what Microsoft is doing.

**Comment by jaimergp** [comment]
We will first need the Python stack built for win-arm64, and that's still WIP.

**Comment by hmaarrfk** [comment]
See https://github.com/conda-forge/conda-forge.github.io/issues/1940 for a more in depth conversation.
