### ISSUE TITLE
Updating base

### ISSUE THREAD

**Issue by gah-bo** [conda-forge/miniforge#553]
### Comment:

I can't find a clear/recent source on this. I am simply wondering if it's OK for me to do 

`mamba update mamba` followed by `mamba update --all` on my base environment to keep it "up to date". I've seen places state the base Python should not be updated, for example, so this is very confusing to me.

Note: I understand I should not `mamba install X` on base, and I have not done that - I have an env per project. I am simply asking if/how I should keep my base env up to date...Sorry for this very trivial question

**Comment by hmaarrfk** [comment]
```
mamba update mamba
mamba update --all
```

should be fine

If you want to remember a single command, from whatever environment you are in.

``` 
mamba update mamba --yes --prefix $(conda info --base)
mamba update --all --yes --prefix $(conda info --base)
```



Honestly, I just call

```
mamba update --all --yes
```

periodically, however, i treat my environments as disposable, so i don't mind having to periodically fully reinstall miniforge.

**Comment by hmaarrfk** [comment]
python for the base environment shouldn't matter so much.

I would stick with python 3.10, but newer is fine too.

Python 3.9 might be too old for fresh installs.

If you have a minimal python 3.8 environment, you can sometimes have some luck with

```
mamba install python=NEW_PYTHON_VERSION
```
to force it to update.
