### ISSUE TITLE
Cannot install in a location different from home directory? 

### ISSUE THREAD

**Issue by julia-luz** [conda-forge/miniforge#560]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hello! 
I'm trying to install in a directory that isn't home. 

Due to a naming issue (my home directory has a different name from my username),  it seems like the installation fails because it still tries to create a .conda file in my home directory. 

`

> Miniforge3 will now be installed into this location:
> /home/myusername/miniforge3
> 
>   - Press ENTER to confirm the location
>   - Press CTRL-C to abort the installation
>   - Or specify a different location below
> 
> [/home/myusername/miniforge3] >>> /array1/myusername/miniforge3
> PREFIX=/array1/myusername/miniforge3
> Unpacking payload ...`

It begins extracting everything as usual, but it suddenly fails with:

`mkdir: cannot create directory ‘/home/myusername/.conda’: No such file or directory
`
I don't really understand why this is an issue if I'm not installing in the home directory? 

### Installed packages

```shell
None
```

### Environment info

```shell
None
```

**Comment by hmaarrfk** [comment]
Closing as it seems that the answer was adequate (no response from OP)

**Comment by julia-luz** [comment]
Ops, sorry about that - it had been so long I completely forgot about this. I ended up getting someone with sudo privileges to delete my user and create a new one by the time this got a reply, so my outputs just wouldn't be relevant anymore. I should have closed this long ago, my bad.

**Comment by hmaarrfk** [comment]
no issue. life happens.

**Comment by hmaarrfk** [comment]
i just don't like to close without explination!
