### ISSUE TITLE
Support for conda develop in Miniforge or Workaround?

### ISSUE THREAD

**Issue by lumoe** [conda-forge/miniforge#564]
### Comment:

I am using Miniforge for environment management and noticed it lacks the `conda develop` command, essential for adding local source folders to the Python path for development. This feature is detailed in the [Conda documentation](https://docs.conda.io/projects/conda-build/en/stable/resources/commands/conda-develop.html) but seems to be missing in Miniforge.

1. Are there plans to include `conda develop` in Miniforge?
2. Can you recommend any workarounds to mimic `conda develop`'s functionality within Miniforge environments?

Thank you for your support and of course for developing Miniforge.

**Comment by hmaarrfk** [comment]
We are trying to keep the installaers pretty minimal. 

"Allowing you to run the `conda` command" is the mission


```
mamba install conda-build
```
??? does that install the required packages?

**Comment by lumoe** [comment]
Worked like a charm!!

Thank you for the incredibly quick response!
