### ISSUE TITLE
Document command line parameters

### ISSUE THREAD

**Issue by hyperknot** [conda-forge/miniforge#57]
I'm trying to install miniforge in a Docker environment, and got into an infinite loop of yes/no questions.
I tried running with `--help`, looking here, in the source files, in the linked issue, but I couldn't find anything about how can I bypass that question.
Finally I tried the `-b` switch from the original miniconda installer and it worked. So I figured out that `-b` is supported in miniforge as well.

Can you document what command line switches are supported exactly?

(Also, it'd be nice to auto-detect interactive shell this so it doesn't even ask yes/no it under docker build.)

**Comment by isuruf** [comment]
```
$ bash Miniforge3-Linux-x86_64.sh -h

usage: Miniforge3-Linux-x86_64.sh [options]

Installs Miniforge3 4.9.0-0

-b           run install in batch mode (without manual intervention),
             it is expected the license terms are agreed upon
-f           no error if install prefix already exists
-h           print this help message and exit
-p PREFIX    install prefix, defaults to $HOME/miniforge3, must not contain spaces.
-s           skip running pre/post-link/install scripts
-u           update an existing installation
-t           run package tests after installation (may install conda-build)
```

**Comment by hyperknot** [comment]
Thanks. Can you add --help as an alias? I don't remember when I used -h instead of --help with command line utilities.

**Comment by isuruf** [comment]
Can you send a PR to https://github.com/conda/constructor/blob/master/constructor/header.sh ?

**Comment by hyperknot** [comment]
I see, so that part is in conda. In that case I think they have their reasons for not going with --double-style.

**Comment by hyperknot** [comment]
In that case I'd just recomment putting your comment into the readme so people can see how to install it.

**Comment by isuruf** [comment]
Added a note to README to check `-h`
