### ISSUE TITLE
Publish 24.3.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/miniforge#581]
Recently we updated to Conda 24.3.0 ( https://github.com/conda-forge/miniforge/pull/574 ) in [Miniforge 24.3.0]( https://github.com/conda-forge/miniforge/releases/tag/24.3.0-0 ). Currently the Miniforge 24.3.0 release is marked as pre-release

What is needed before we can mark it as latest?

**Comment by jakirkham** [comment]
cc @hmaarrfk

**Comment by hmaarrfk** [comment]
I forgot lol.

some builds had failed. They seem to have passed now.

**Comment by jakirkham** [comment]
Oh ok cool. Thanks Mark! 🙏
