### ISSUE TITLE
Vote to update to 3.11 or 3.12 - Ends June 23

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/miniforge#598]
### Comment:

I don't think there is much to discuss.

We last updated to 3.10 about 2 years ago.

We should likely update again.

Let use emojis to vote.

Maintainer of `miniforge` very much encouraged.
Conda-forge core welcome.

Voting shall close June 23.

Use emojis to vote.

* 🚀 3.12
* 🎉 3.11
* 👀 3.10

**Comment by hmaarrfk** [comment]
For the larger community passerby's if you want your voice to be heard, it would be interesting to keep you distinct from the maintainers 

Use emojis to vote.

*  🚀 3.12
*  🎉 3.11
*  👀 3.10

Please vote here, it may affect my one vote ;)

**Comment by hmaarrfk** [comment]
Core member votes:

- 3.11 -- @jakirkham @isuruf @jaimergp 
- 3.12 -- @hmaarrfk @jaimergp @ocefpaf 

Community vote: 3.12

**Comment by jakirkham** [comment]
@jaimergp did you mean to select both?

**Comment by hmaarrfk** [comment]
Well seems like a good old draw.

I'll leave it to the first person to press merge between:
- https://github.com/conda-forge/miniforge/pull/603
- https://github.com/conda-forge/miniforge/pull/604

**Comment by jaimergp** [comment]
Let's do Python 3.12 then :)

**Comment by jakirkham** [comment]
The main thing is to make sure all our tooling (like for bots and webservices) is available on Python 3.12

**Comment by mbargull** [comment]
Either version works for me (slight preference for 3.12).
-   Pro for 3.11: More stable in terms of downstream support.
-   Pro for 3.12: We have to update at some point to not get unnecessarily far behind again and 3.12 will be the expected baseline soon (since 3.13 is well into beta already).
    (I would've suggested we make sure to update not later than Q4 2024; now it's nearly start of Q3 -- not too far off...)

**Comment by hmaarrfk** [comment]
I've been "skipping odd versions" of python in my personal projects. Too much churn otherwise.

The pydantic hiccup did scare me though.... but I guess thats life.

**Comment by hmaarrfk** [comment]
Thank you all for your feedback. It seems that there is momentum behind the 3.12 update.

It may take an other week to get pushed since we want to synchronize it with a few other backward incompatibility changes
