### ISSUE TITLE
A virus scan information

### ISSUE THREAD

**Issue by robinsds** [conda-forge/miniforge#605]
### Comment:

A Win32/Heur.Generic.HxQBVyoA virus was found in the downloaded file, is this a false positive?
URL：https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Miniforge-pypy3-Windows-x86_64.exe
MD5：8dee47242868b65fdc96da90a7dcc205

**Comment by hmaarrfk** [comment]
Probably, they are all automatically generated and uploaded from our CIs.
