### ISSUE TITLE
Back to default settings?

### ISSUE THREAD

**Issue by herry23xet** [conda-forge/miniforge#616]
### Comment:

Is there a way to reset Miniforge/Mambaforge to the original settings? In other words, the settings that you have when you install Miniforge/Mambaforge from scratch.
That is, without uninstalling it and then reinstalling it?

And also a small supplementary question:
Python will be soon to be upgraded to version 12.* in the Base Environment. If I already have Miniforge/Mambaforge, does the version upgrade happen automatically by running `mamba update mamba` resp. `mamba update --all`?

**Comment by hmaarrfk** [comment]
Deleting the file 

`/home/herry/.condarc`

Is the only thing I can think of. Before deleintg the file check the contents to understand what you are deleting

Unfortunately the state of your packages cannot be reversed easily.

**Comment by hmaarrfk** [comment]
I'll take the thumbs up as resolved.
