### ISSUE TITLE
Inaccurate info re Mambaforge deprecation in README FAQ

### ISSUE THREAD

**Issue by orbsmiv** [conda-forge/miniforge#625]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The FAQ section of the `README.md` file contradicts the info found elsewhere regarding the upcoming deprecation of the Mambaforge package.

- <https://github.com/conda-forge/miniforge#whats-the-difference-between-mambaforge-and-miniforge>
- <https://github.com/conda-forge/miniforge/blob/2e5c890fbed28b88cd6683eb4f5403d25123abdf/README.md?plain=1#L281>

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by hmaarrfk** [comment]
I've added this to our list of things to do: https://github.com/conda-forge/miniforge/issues/602
