### ISSUE TITLE
base env still pinned at 3.10.*

### ISSUE THREAD

**Issue by wrb2012** [conda-forge/miniforge#644]
### Comment:

after `bash Miniforge-xx-xx.sh -u`,  mamba 1.5.8 still shows pinned package: python=3.10.*
and `mamba update -n base mamba` will fail, delete `mamba` itself.
This problem will mitigate after
`conda install python=3.12.5`

I have look base env, there is no `pinned` in conda-meta and I removed python_abi_3.10

**Comment by hmaarrfk** [comment]
You removed the version information of MIniforge that you are using.

If you use one from the tag:
https://github.com/conda-forge/miniforge/releases/tag/24.7.1-0

it will be python 3.12.

**Comment by jaimergp** [comment]
> I have look base env, there is no pinned in conda-meta and I removed python_abi_3.10

This is the standard behaviour for mamba and conda. It will pin your current Python version so it doesn't "jump" to a newer one, which would cause the reinstallation (if lucky) of all your Python-dependent packages.
