### ISSUE TITLE
Miniforge3-Linux-x86_64 installation issue: critical libmamba Specified pkgs_dir does not exist

### ISSUE THREAD

**Issue by AndHerr** [conda-forge/miniforge#646]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Hi! 

I'm just trying to install miniforge as an alternative to miniconda, but I'm getting the following bug during the installation: critical libmamba Specified pkgs_dir does not exist. Do I need to download any package to install miniforge?

Thanks in advance!

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by jsta** [comment]
I am seeing this error. Can you say what was the solution?

**Comment by ANDdna1991** [comment]
I had a previous .condarc file pointing to the old pkgs_dir folder which didn't exist. I just removed the .condarc file. Hope it helps.

Thanks
