### ISSUE TITLE
Update FAQ for Mambaforge deprecation

### ISSUE THREAD

**Issue by zmoon** [conda-forge/miniforge#648]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/conda-forge/miniforge/pull/615 missed updating the FAQ, it looks like:

https://github.com/conda-forge/miniforge/blob/de8fc9f14918001e3bb348e7e2f8ea2f7c7af11d/README.md?plain=1#L310-L317

### Installed packages

```shell
conda list
```

### Environment info

```shell
conda info
```

**Comment by hmaarrfk** [comment]
Thank you. in the future. PRs welcome.
