### ISSUE TITLE
Feature request: Miniforge for Termux (Android)

### ISSUE THREAD

**Issue by oddrationale** [conda-forge/miniforge#65]
It would be really cool to get Miniforge working on Android via [Termux](https://termux.com)!

This is what I've tried so far:

Most Android devices are ARM. I can confirm this by running `uname -m` in Termux:
```bash
❯ uname -m
aarch64
```
So I downloaded the latest aarch64 installer on the Miniforge releases page. I tried running the installer, but ran into this issue:
```bash
❯ bash Miniforge3-Linux-aarch64.sh -ub
PREFIX=/data/data/com.termux/files/home/miniforge3
Unpacking payload ...
Miniforge3-Linux-aarch64.sh: line 318: /data/data/com.termux/files/home/miniforge3/conda.exe: No such file or directory
Miniforge3-Linux-aarch64.sh: line 320: /data/data/com.termux/files/home/miniforge3/conda.exe: No such file or directory
```
The error message is strange because if I `ls` the directory, I can see the file there:
```bash
❯ ls -l /data/data/com.termux/files/home/miniforge3/
total 9648
-rwx------ 1 u0_a329 u0_a329 9871336 Nov 21 15:26 conda.exe
```
Reading up on the [Termux Wiki](https://wiki.termux.com/wiki/Differences_from_Linux), they've noted several differences between Termux and a standard Linux distribution. From what I can gather, I would need to recompile the `conda.exe` executable to be properly linked to the shared libraries in the Termux locations.

Any tips on how I might accomplish this? Thanks!

**Comment by isuruf** [comment]
It's not as simple as that. We'll have to recompile all of the packages with the android NDK. This would need a lot of work to enable a base distribution and conda packages on top. The correct place to discuss this would be https://github.com/conda-forge/conda-forge.github.io

**Comment by oddrationale** [comment]
That makes sense. I didn't realize it would also involve recompiling all the packages with the Android NDK.

One can only dream. I'll close this issue for now.
