### ISSUE TITLE
Stucked when Installing miniforge on ubuntu server

### ISSUE THREAD

**Issue by indexofire** [conda-forge/miniforge#659]
### Comment:

When I installed miniforge by:

```
bash Miniforge3-24.7.1-2-Linux-x86_64.sh -b -p $HOME/.mamba

PREFIX=/data/yanjiaqi/.mamba

Transaction
  
  Prefix: /data/yanjiaqi/.mamba/envs/_virtual_specs_checks

  All requested packages already installed

Dry run. Not executing the transaction.
Unpacking payload ...
Extracting _libgcc_mutex-0.1-conda_forge.tar.bz2
Extracting ca-certificates-2024.8.30-hbcca054_0.conda
Extracting ld_impl_linux-64-2.40-hf3520f5_7.conda
Extracting pybind11-abi-4-hd8ed1ab_3.tar.bz2
Extracting python_abi-3.12-5_cp312.conda
Extracting tzdata-2024a-h8827d51_1.conda
Extracting libgomp-14.1.0-h77fa898_1.conda
Extracting _openmp_mutex-4.5-2_gnu.tar.bz2
Extracting libgcc-14.1.0-h77fa898_1.conda
Extracting libexpat-2.6.3-h5888daf_0.conda
Extracting libgcc-ng-14.1.0-h69a702a_1.conda
Extracting libstdcxx-14.1.0-hc0a3c3a_1.conda
Extracting openssl-3.3.2-hb9d3cd8_0.conda
Extracting bzip2-1.0.8-h4bc722e_7.conda
Extracting c-ares-1.32.3-h4bc722e_0.conda
Extracting keyutils-1.6.1-h166bdaf_0.tar.bz2
Extracting libev-4.33-hd590300_2.conda
Extracting libffi-3.4.2-h7f98852_5.tar.bz2
Extracting libiconv-1.17-hd590300_2.conda
Extracting libnsl-2.0.1-hd590300_0.conda
Extracting libstdcxx-ng-14.1.0-h4852527_1.conda
Extracting libuuid-2.38.1-h0b41bf4_0.conda
Extracting libxcrypt-4.4.36-hd590300_1.conda
Extracting libzlib-1.3.1-h4ab18f5_1.conda
Extracting lzo-2.10-hd590300_1001.conda
Extracting ncurses-6.5-he02047a_1.conda
Extracting reproc-14.2.4.post0-hd590300
......

  Summary:

  Install: 85 packages

  Total download: 0 B

─────────────────────────────────────────────────────────────────────────────────────



Transaction starting
```
It stucked at 'Transaction starting'. Ctrl + C to terminanted the process, all mamba/conda settings were not finished.

**Comment by indexofire** [comment]
when ps waux  | grep `whoami`

it showed so many `/data/yanjiaqi/.mamba/bin/python3.12 -Wi -u /data/yanjiaqi/.mamba/install_tmp/mambaf8v4WL4CMuF` processes with status S+.

**Comment by hmaarrfk** [comment]
do you have a previous installation by any chance? there are bugs with installing when conda or mamba already exists.

**Comment by indexofire** [comment]
> do you have a previous installation by any chance? there are bugs with installing when conda or mamba already exists.

no, it's a new installation on a AMD CPUS Ubuntu server. the problem has been solved by administrator loging as the user account to install. the only differences which I known was `sh  Miniforge3-24.7.1-2-Linux-x86_64.sh`  and I used `bash Miniforge3-24.7.1-2-Linux-x86_64.sh`.

I canot remake the problem on my own PC so I dont know if it's the reason.

**Comment by hmaarrfk** [comment]
I tried to use `sh` to install Miniforge in https://github.com/conda-forge/miniforge/pull/655 seems to work. (the other failures are due to docker failing to find an image... grrrr)

Maybe we have some incompatibility with `${HOME}/.mamba`

I'm tempted to close since it seems like you have moved on, but if you hit this again, do recomment and we can reopen.

**Comment by indexofire** [comment]
> I tried to use `sh` to install Miniforge in [#655](https://github.com/conda-forge/miniforge/pull/655) seems to work. (the other failures are due to docker failing to find an image... grrrr)
> 
> Maybe we have some incompatibility with `${HOME}/.mamba`
> 
> I'm tempted to close since it seems like you have moved on, but if you hit this again, do recomment and we can reopen.

thanks!

**Comment by indexofire** [comment]
I have finished `bash` to install miniforge on other ubuntu server. So the stucked process was caused by server settings maybe.

**Comment by jakirkham** [comment]
Would highly recommend using [`tmux`]( https://github.com/tmux/tmux ) or [GNU `screen`]( https://www.gnu.org/software/screen/ ) when running things on a remote machine

Too many things can go wrong with the connection, so these two tools are quite helpful as they keep the session running (even if you have been disconnected)
