### ISSUE TITLE
A question about "mamba list" and "mamba env list"

### ISSUE THREAD

**Issue by HenryZhang-git** [conda-forge/miniforge#668]
### Comment:

Hi,bro,Im facing a quetison about mambaforge. I have install some packages, but then, some errors are coming:
When I run the code "mamba list" or "mamba env list",  there is error.
`(jax) henry@henry:~$ mamba list
Traceback (most recent call last):
  File "/home/henry/mambaforge/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/henry/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/henry/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/henry/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
`.
But, when i run "conda list" or "conda env list",these code can be run.
How can I do? Thanks!

**Comment by hmaarrfk** [comment]
I have a feeling you are hitting: https://conda-forge.org/docs/user/transitioning_from_defaults/

Your environment is likely broken, try to reinstall miniforge3.

* Delete previous installations of conda
* Remove any environment variables from your `.bashrc`
* Reinstall according to our instructions

**Comment by hmaarrfk** [comment]
To get more help, please provide the information requested in the issue template providing information about conda list and conda info. 

To make this easy for you, I'm going to close this. do feel free to re-open an issue filling out all the requested sections to the best of your ability
