### ISSUE TITLE
cudatoolkit new version (12.x.x)

### ISSUE THREAD

**Issue by ArkadySkv** [conda-forge/miniforge#672]
### Comment:

Could you please update in miniforge cudatoolkit version, up it to 12.x.x?

**Comment by hmaarrfk** [comment]
the miniforge installer does not contain the cuda toolkit. That must be installed after the fact. Update it as you would any other package.

**Comment by ArkadySkv** [comment]
> the miniforge installer does not contain the cuda toolkit. That must be installed after the fact. Update it as you would any other package.

Ok then I will do that

**Comment by jakirkham** [comment]
Please see [these docs]( https://github.com/conda-forge/cuda-feedstock/blob/main/recipe/README.md )
