### ISSUE TITLE
Since Mambaforge will be deprecated in July 2024, should I use `conda` instead of `mamba`?

### ISSUE THREAD

**Issue by sj-ganwh** [conda-forge/miniforge#676]
### Comment:

Since Mambaforge will be deprecated in July 2024, should I use `conda` instead of `mamba`? Or are these two commands independent?

**Comment by hmaarrfk** [comment]
We aren’t really planning to remove the mamba command today. We are just reducing the number of installers we have to create for now. 

Use mamba or conda as you wish. In 2024 with conda lib mambasolver the performance should be very close

**Comment by jakirkham** [comment]
For clarity, Miniforge also includes `mamba`.

Today Miniforge and Mambaforge install the same things. They are just named differently.
