### ISSUE TITLE
Windows 11 'powershell' is not a recognized internal or external command

### ISSUE THREAD

**Issue by sxwebster** [conda-forge/miniforge#680]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

When installing miniforge on Windows 11 the installation errors out because it cannot find powershell. By default on Windows 11 (pro, at least) powershell is not registered in the environment variables for PATH. 

It may be worth considering implementing a detection to determine if powershell is a recognised command, and if not testing the default path and using that. 

The default setting people need to set up in PATH is:
```
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
```

The installer could test for the above, and if not fail over to the below. 

```
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "your command"
```

### Installed packages

```shell
Nil. Clean install. Miniforge is the first installed item besides the raw OS Windows 11.
```

### Environment info

```shell
Unable to run as not installed. Failing installer.
```

**Comment by hmaarrfk** [comment]
which exe filename did you download. please be explicit there are a few different ones that invoke different codepaths today.

**Comment by sxwebster** [comment]
Miniforge-pypy3-24.9.2-0-Windows-x86_64.exe

**Comment by hmaarrfk** [comment]
Pypy3 is deprecated and it is likely our warning message being triggered.

I know it is the first link, but this will be removed in the coming months, please use ` Miniforge3-Windows-x86_64.exe`

**Comment by sxwebster** [comment]
Understood, thank you.

**Comment by Rabijns** [comment]
I had the same issue on windows 10 today and can confirm that the solution of @hmaarrfk works. Thanks
