### ISSUE TITLE
Remove all pypy builds

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/miniforge#702]
I was surprised to see that the latest miniforge [release](https://github.com/conda-forge/miniforge/releases/tag/24.11.0-0) still has plenty of pypy artefacts. We dropped that across all of conda-forge, so providing installers there is at best confusing and at worst detrimental

**Comment by hmaarrfk** [comment]
They are being deprecated with a plan to remove them in jan

**Comment by h-vetinari** [comment]
Using pypy in the base environment was never even close to the most relevant use case for pypy, and keeping it in miniforge longer than we kept building up to date packages for pypy is... surprising. I consider this an illusion of support at best, but 🤷‍♂️
