### ISSUE TITLE
Endless xcode prompts when installing on apple silicon without xcode

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/miniforge#71]
When installing on a fresh apple silicon machine the installer results in a seemingly endless stream of:
```
You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Return key to view the license agreements at '/Applications/Xcode-beta.app/Contents/Resources/English.lproj/License.rtf'
```
with the full license shown in between. It's also hard to quit as all keyboard shortcuts I tried don't actually kill the installer.

Can this be avoided? If not, can the installer detect that the license hasn't been accepted before continuing?

**Comment by chrisburr** [comment]
It looks like it is actually needed as `conda --help` returns 137 without.

**Comment by isuruf** [comment]
what uses xcode in `conda --help`?

**Comment by chrisburr** [comment]
My guess was that these lines were failing due to the license having not been accepted:
```
/Users/chrisburr/miniforge3/.condatmp/a48c082d-09eb-48f4-a13b-65524668c59d: replacing existing signature
```
but I don't know what they're actually doing

**Comment by hmaarrfk** [comment]
Did you get an M1 laptop?! Cool

**Comment by chrisburr** [comment]
I haven't seen this anywhere else so it might have been a quirk of the system I was originally using. I'll close in the hope it's not actually a problem.
