### ISSUE TITLE
Non-full URL channels problematic when using channel_alias

### ISSUE THREAD

**Issue by krisevans** [conda-forge/miniforge#78]
The use of non-full URLs in the `.condarc` that results from: 

https://github.com/conda-forge/miniforge/blob/88a8a86172b3b585652f9f6ea285f044ba124b9c/Miniforge3/construct.yaml#L8-L13

breaks the resolving of channels when using a `channel_alias`:

https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#channel-alias

**Comment by hmaarrfk** [comment]
I think this is more of a feature. maybe.

**Comment by isuruf** [comment]
Yes, it's a feature.
