### ISSUE TITLE
Cannot install packages from a Gitlab PyPI-compatible package repository

### ISSUE THREAD

**Issue by ArneBachmann** [conda-forge/miniforge#79]
- [X ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

## Issue
It's a bit difficult to explain and reproduce... In a bootstrap-script I switched from Miniconda3 to Miniforge3, which fails in the last action:

- The script downloads and installs Miniforge3 into a sub-folder (no changes to registry)
- `conda install -y -n base python=3.8`  # install correct python into base
- `pip install win-unicode-console`  # avoid problems with non-unicode console settings
- `conda install -y PyCrypto ruamel.yaml psutil pywin32`  # requirements that fail to install with pip
- `copy /Y "%PYTHON_FOLDER%\Library\bin\libcrypto-1_1-x64.*" "%PYTHON_FOLDER%\DLLs"\ >nul 2>&1`  # workaround for a recent problem
- `copy /Y "%PYTHON_FOLDER%\Library\bin\libssl-1_1-x64.*"    "%PYTHON_FOLDER%\DLLs"\ >nul 2>&1`
- `pip install -U --extra-index-url https://pypi:***@gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple --trusted-host https://gitlab.dlr.de  autocook`

The last install line, however, fails with the error
```Powershell
ERROR: Requested autocook from https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/files/20c71b4a4ae271fd7a9acfd0fe49051c45f0de3bd8ccd2ce198db58128055372/autocook-1.202012.91115.tar.gz#sha256=20c71b4a4ae271fd7a9acfd0fe49051c45f0de3bd8ccd2ce198db58128055372 has different version in metadata: '1.202012.91129'
```

The conflicting timestamp is always the *current time* (!), not the one contained in the filename or archive metadata.
I think there's a problem with the pip that comes with Miniforge3.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
This looks rather like a `pip` issue not a conda-(forge) related one. Maybe it's surfacing because Miniforge comes with a newer version of pip?

**Comment by jakirkham** [comment]
Or possibly even a PyPI mirror setup issue?

**Comment by ArneBachmannDLR** [comment]
After I update pip manually, I get the `different version in metadata` in a loop 15 times before `no matching...`.
I can reproduce it with my bootstrap script, but not with the steps above, maybe linked to `PATH` settings.

```
D:\forks\HACE\autocook>pip install --extra-index-url https://pypi:H3yzAC-cLS_iYMsHkDQM@gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple --trusted-host https://gitlab.dlr.de  "autocook==1.202012.151046"
Looking in indexes: https://pypi.org/simple, https://pypi:****@gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple, https://pypi:****@gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple
Collecting autocook==1.202012.151046
  Downloading https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/files/05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f/autocook-1.202012.151046.tar.gz (571 kB)
     |████████████████████████████████| 571 kB 3.2 MB/s
  WARNING: Requested autocook==1.202012.151046 from https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/files/05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f/autocook-1.202012.151046.tar.gz#sha256=05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f, but installing version 1.202012.151047
WARNING: Discarding https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/files/05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f/autocook-1.202012.151046.tar.gz#sha256=05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f (from https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/simple/autocook/) (requires-python:>=3.5). Requested autocook==1.202012.151046 from https://gitlab.dlr.de/api/v4/projects/8670/packages/pypi/files/05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f/autocook-1.202012.151046.tar.gz#sha256=05f04cf8f44748b63561f67e06dfe5c446d88f8e45b223930fcca0ef1ff54d5f has different version in metadata: '1.202012.151047'
ERROR: Could not find a version that satisfies the requirement autocook==1.202012.151046
ERROR: No matching distribution found for autocook==1.202012.151046
```

But I think I know what the problem is: 
The version of the packaged tool is computed when running `setup.py` during packaging time.
When I install the package with CondaForge, however, there is a call in `pip\_internal\operations\build\metadata_legacy.py(70)generate_metadata()` to a subprocess that runs pip egg_info`, which in turn creates a new timestamp in the isolated installation during installation. I'm confident this is part of the problem.

I'm still wondering why this only appear when using condaforge, though.

**Comment by ArneBachmann** [comment]
**TL;DR**: Root cause unknown, but specific problem caused by maintainer error (dynamically computing the Python package version when running `setup.py`).

It was never a problem with miniconda, but surfaced with condaforge, which is actually good.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @ArneBachmannDLR)
