### ISSUE TITLE
Fix deploy Travis key

### ISSUE THREAD

**Issue by hadim** [conda-forge/miniforge#8]
I tried multiple time to release to GH using Travis but each time I have a credential error in Travis: https://travis-ci.com/conda-forge/miniforge/builds/137501455#L1663

Can someone push the correct `deploy` section to `.travis.yml` please?

If you want to try multiple time, it's ok to delete a tag to recreate it:

```
git tag -d 4.7.12
git push upstream :4.7.12
git tag 4.7.12
git push upstream master --tags
```

**Comment by isuruf** [comment]
Fixed now. Needed to encrypt for .com

**Comment by hmaarrfk** [comment]
Gah, sorry
