### ISSUE TITLE
Packages not found error

### ISSUE THREAD

**Issue by slerman12** [conda-forge/miniforge#80]
Brand new M1 MacBook, fresh everything. Just ran 'conda install -c pytorch pytorch' and got his error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pytorch

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
```

**Comment by rgommers** [comment]
There aren't any released pytorch packages for `osx-arm64` yet, so this is not surprising. You can grab a nightly wheel or build from source I think, see https://github.com/pytorch/pytorch/issues/48145

**Comment by hmaarrfk** [comment]
I guess we are closing because:
1. We know this is a very popular package.
2. Packaging this for OSX-arm64 is going to be challenging.
3. Repackaging everything on conda-forge for OSX-arm64 is already on the roadmap.

i hope you have fun with your new toy @slerman12 :D

**Comment by slerman12** [comment]
Thanks, I'll try that. Would installing Gym/atari work?

**Comment by hmaarrfk** [comment]
i'm not so sure. You will have to experiment with functionaly.

Honestly, hold on to your old workstation for a while. The transition won't be instant, and working with bleeding edge hardware accelerated software is going to take a while.

https://anaconda.org/pytorch/pytorch/files

Pytorch doesn't list any build for osx other than `osx-64` so your mileage may varry.

**Comment by slerman12** [comment]
I tried installing pytorch from source using mini forge and got this error at the end of installation:

`error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "11.0" during configure`

**Comment by slerman12** [comment]
I was able to install pytorch from source. Works, no problem. Is there a way I can now use it with Gym? Can I install gym without the apple silicon compatibility?

**Comment by hmaarrfk** [comment]
again, i'm not sure.

**Comment by slerman12** [comment]
Is there something wrong with the NumPy distribution? Running `np.empty(2)` returns an array of non-NaNs.

**Comment by rgommers** [comment]
> Is there something wrong with the NumPy distribution? Running `np.empty(2)` returns an array of non-NaNs.

That's normal. `empty` doesn't give you nans, it gives you whatever random data is already present in the block of memory it grabs.

**Comment by slerman12** [comment]
Ah yes, I thought that was the cause of the inconsistency in performance of my code but it must be something else then. It’s very odd. My model performs well on my old MacBook, but the exact same code gets much worse results on my new M1 MacBook with Pytorch and gym installed from source, and everything else installed with miniforge’s conda.
