### ISSUE TITLE
Document that OSX-Arm64 installs python 3.9 not 3.8

### ISSUE THREAD

**Issue by dionmes** [conda-forge/miniforge#81]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Latest installer installs python 3.9 not 3.8 as it says in the documentation.

<br/>

OS X | arm64 (Apple Silicon) | Miniforge3-MacOSX-arm64
-- | -- | --

**Comment by hmaarrfk** [comment]
We only have python 3.9 for OSX arm64.

This is the intended behavior.

It is very likely that Python 3.8 and Python 3.7 will not be supported on OSX ARM 64.

If you do think that is important, please open an issue with the python feedstock.

Here is the note about the release process.
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by isuruf** [comment]
Maybe we can add a note that it is 3.9. We also have 3.8, but it's not yet officially supported by PSF. If you want a 3.8 env, you can create a new env.

**Comment by hmaarrfk** [comment]
Ah, i see you have a build for it:

osx-arm64/python-3.8.6-h12cc5a1_1_cpython.tar.bz2

yeah, we can add a note.

**Comment by dionmes** [comment]
Hm, maybe I am missing the point. I was looking at [https://github.com/conda-forge/miniforge](https://github.com/conda-forge/miniforge) .it says` "Latest installers with python 3.8 in the base environment"`

**Comment by hmaarrfk** [comment]
Right. There is an asterix that is missing.

Where we would say. "Except for OSX-arm64, where Python 3.9 is installed".

A PR is welcome making that explicit in the readme.



Please note that OSX-arm64 is VERY new. We are trying to ensure that software is migrated, but it will take time.

**Comment by dionmes** [comment]
Yes I know, but its fun experimenting. I already think you are doing an awesome job. I can make that PR if you want.

**Comment by hmaarrfk** [comment]
that would be great! Thanks.

**Comment by dionmes** [comment]
Added the note in the readme and made the PR.

**Comment by hmaarrfk** [comment]
Awesome
