### ISSUE TITLE
Can't add certain installed packages to new environments

### ISSUE THREAD

**Issue by slerman12** [conda-forge/miniforge#84]
When I do `conda list`, I can see two of the included packages listed:

```
torch                     1.8.0a0                  pypi_0    pypi
torchvision               0.9.0a0+83171d6          pypi_0    pypi
```

However, when I do `conda create -n myenv torch torchvision`, I get this error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision
  - torch
```

**Comment by isuruf** [comment]
That's because you installed `torch` with pip and not conda. There's no `torch` package in conda-forge yet.

**Comment by slerman12** [comment]
Oh, is there still a way to include those packages in a new env?
