### ISSUE TITLE
Generate/backfill SHA256SUMS

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/miniforge#90]
The release page generation on #89 spends a lot of its time downloading the individual `.sha256` files. It would be nice if, at the end of a full run, a top-level `SHA256SUMS` file was generated from the concatenated files (or just recalculate the whole thing) and added to a release. Having these back-filled for historical releases would also be nice.

**Comment by hmaarrfk** [comment]
While this would be nice, I don't think there has been any desire to do it in 3 years.
