### ISSUE TITLE
What to do about "latest"?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/miniforge#91]
In the wild (and even on this repo!) a lot of workflows use `setup-miniconda` with `miniconda-version: latest`. As we'll soon be supporting the Miniforges directly, it would be good to have an approach to this. Some ideas:
- mutable tag
  - I don't like it much, but it would probably work
- redirects
  - has to at least work with `curl` and whatever GitHub actions does under the hood, etc. so not sure if it can be an HTML page

**Comment by isuruf** [comment]
We already have latest links. See https://github.com/conda-forge/miniforge#download

**Comment by bollwyvl** [comment]
I see that README.md hasn't changed for 17 days, but there _has_ been a release since then, and the SHAs line up from the `latest` link. How's that dark magic work? I guess i have to go look at the github docs... 

Anyhow, closing, can use this knowledge over on `setup-miniconda` i suppose, though these now have a _slightly_ different URL structure...

**Comment by bollwyvl** [comment]
sure enough, right in here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/linking-to-releases

the more you know :star2:
