### ISSUE TITLE
Homebrew installer

### ISSUE THREAD

**Issue by domoritz** [conda-forge/miniforge#93]
It would be awesome if there were a Formula for homebrew so one can just run `brew install --cask miniforge` just like one can do `brew install --cask miniconda`.

**Comment by domoritz** [comment]
The installer could be very similar to https://github.com/Homebrew/homebrew-cask/blob/master/Casks/miniconda.rb but also change which installer to pull based on the architecture (e.g. arm could pull a different script).

**Comment by isuruf** [comment]
Sounds good. Can you send a PR to https://github.com/Homebrew/homebrew-cask?

**Comment by domoritz** [comment]
Done in https://github.com/Homebrew/homebrew-cask/pull/97278. I haven't found a good way to support multiple architectures, though.

**Comment by domoritz** [comment]
Merged.
